### ISSUE TITLE
Desktop percentage

### ISSUE THREAD

**Issue by Yoanndp** [DarkFlippers/unleashed-firmware#100]
### Describe the bug.

When you change the battery view, it doesn't change on the desktop. The view requires a reboot (Holding `Left` + `Back`) to get updated.

### Reproduction

1. Go to `Menu`
2. Select the `Settings` sub menu
3. From there, pick `Desktop` 
4. Finally, change the `Battery View` to whatever you want

### Target

un1-906124 [10-10-2022]

### Logs

```Text
N/A
```

**Comment by xMasterX** [comment]
Its not a bug, its how it was implemented, to avoid reading int memory every tick

In place where we updating screen we don't know when settings was updated, and we can't force update it right after change
It does not require reboot(but yes you can use it to speed up process), it will update automatically when battery percentage change or if you connect charger

**Comment by Yoanndp** [comment]
Alright, it makes sense now. Thank you !
