### ISSUE TITLE
Explaining "🎲 Download extra apps pack" link in release pages

### ISSUE THREAD

**Issue by pdostal** [DarkFlippers/unleashed-firmware#104]
### Describe the enhancement you're suggesting.

Hello,

there is a link in repository release page:
> [🎲 Download extra apps pack](https://download-directory.github.io/?url=https://github.com/UberGuidoZ/Flipper/tree/main/Applications/Unleashed)

Can you shortly explain what "extra apps pack" is? Or can you add a link to a page where it is explained?

**Comment by xMasterX** [comment]
Check out readme here:
https://github.com/UberGuidoZ/Flipper/tree/main/Applications/Unleashed

**Comment by pdostal** [comment]
ok, well thank you
