### ISSUE TITLE
Infrared issues

### ISSUE THREAD

**Issue by casper89d** [DarkFlippers/unleashed-firmware#110]
### Describe the bug.

Infrared "Read" has been detecting IR Signals erroneously, even while the IR sensor is shielded/blocked, then again with the device completely wrapped in foil. This is also observed with the debug option enabled.

### Reproduction

1.While blocking Infrared, select Infrared menu option "Learn New Remote" or, with flipper debug option enabled, select "Debug" to open the Infrared Monitor.
2. The "Learn New Remote" option will detect a small number of samples from an unknown source, while "Debug" Infrared Monitor will average approximately 3 to 15 samples.

**Comment by xMasterX** [comment]
this is how flipper hardware is made, if you think this is software issue, create it in official repo
