### ISSUE TITLE
Dummy Mode shortcut to GAMES list

### ISSUE THREAD

**Issue by Stefo0** [DarkFlippers/unleashed-firmware#112]
### Description of the feature you're suggesting.

Hi,
If I activate the Dummy Mode on the Flipper Zero the OK button opens directly the Snake game. 
Is it possible to change it and show the game list instead of opening Snake Game? Otherwise is not possible to play any other game if Dummy Mode is activated.

If it's not possible, how can I set another game as default game in Dummy Mode?

Thanks..

**Comment by TQMatvey** [comment]
well this should be implemented on the official side, as dummy mode is the official featur that they should develop, currently you cannot set any other game in dummy mode..

**Comment by Stefo0** [comment]
Thanks..

**Comment by TQMatvey** [comment]
> Thanks..

Thats actually a very interesting topic, i am trying to make it to work also right now, the problem is that if i open games folder on dummy mode, you can still go out to other FAPs which is very bad :<

**Comment by Stefo0** [comment]
Is possible to create a selection option (like the Desktop/Primary Favorite App...it could be named Dummy Favorite App) where the user can decide what to open in Dummy Mode? He can select one of the games available or the game list.

**Comment by TQMatvey** [comment]
possible but difficult

**Comment by RogueMaster** [comment]
This should help fix this... or at least improve on it... #137

**Comment by xMasterX** [comment]
This was implemented in PR #137 from RogueMaster but not yet user customisable, this will be for next time
