### ISSUE TITLE
A way to take screen shots

### ISSUE THREAD

**Issue by ALD53105** [DarkFlippers/unleashed-firmware#116]
### Description of the feature you're suggesting.

I would love the ability to press a key or sequence of keys to save a screenshot of what is currently displayed on FlipperZero. This seems like a basic function on almost any current device with a screen has and is missing from FlipperZero software currently.

### Anything else?

The screenshots don't even need to be able to be viewed on the device to be useful. If all that was saved was a screenshot that could be accessed in a folder via a computer later, that would be great.

**Comment by xMasterX** [comment]
You can make screenshot in qflipper
