### ISSUE TITLE
un1, un2, un3?

### ISSUE THREAD

**Issue by patrick7** [DarkFlippers/unleashed-firmware#118]
### Describe the enhancement you're suggesting.

What's the difference?

**Comment by xMasterX** [comment]
un = unleashed
1,2,3,... build number (increments when official commit doesn't change)
-abcdef = official repo commit sha number

**Comment by patrick7** [comment]
Thanks! I'm not sure if I got it right. There's an un1, un2 and un3 with the same SHA. So this are multiple builds based on the same code? Which one should I use?

**Comment by xMasterX** [comment]
SHA from official commit, our commits sha numbers is not shown in version itself, you can find it in about screen
> Which one should I use?

Latest one

**Comment by derskythe** [comment]
@xMasterX maybe you trying to switch to OFW version number with some extra name? I thinking about it and even for me this naming not such transparent and obvious.
And for an unprepared audience, such names can be just scary. 
Trust me

**Comment by xMasterX** [comment]
Version naming changed now, see changelog
