### ISSUE TITLE
Name change instructions do not work

### ISSUE THREAD

**Issue by heyquentin** [DarkFlippers/unleashed-firmware#120]
### Describe the bug.

Following the instructions to change the name shown on the Flipper does not result in a name change.

### Reproduction

1. Read [How to build](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/HowToBuild.md) and [How to install](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/HowToInstall.md) to know how to build and install firmware
2. Follow how to build instructions to prepare all things before continuing
3. Run release build to verify all is ok - ./fbt COMPACT=1 DEBUG=0 updater_package
4. Clear build files - ./fbt COMPACT=1 DEBUG=0 updater_package -c
5. Run command with extra enviroment var before ./fbt that variable should contain your custom name in alphanumeric characters - max length 8 chars CUSTOM_FLIPPER_NAME=Name ./fbt COMPACT=1 DEBUG=0 updater_package - where Name write your custom name
6. Copy dist/f7-C/f7-update-local folder to microSD update/myfw/ and run update file on flipper from file manager app (Archive)
7. Flash from microSD card only!!!! .dfu update from qFlipper will not work properly since name and serial number will be changed 
8. Done, you will have custom name, serial number and bluetooth mac address
9. Also you can skip 5-7 and flash with CUSTOM_FLIPPER_NAME=Name ./fbt COMPACT=1 DEBUG=0 FORCE=1 flash_usb_full

**Comment by xMasterX** [comment]
Bug can’t be replicated, all works fine for me, also not only me, we just tested it on latest dev
Seems you did something wrong or don't read Troubleshooting section
