### ISSUE TITLE
Remove Payment card NFC restrictions

### ISSUE THREAD

**Issue by ALD53105** [DarkFlippers/unleashed-firmware#123]
### Describe the enhancement you're suggesting.

It would be nice to have the restrictions on saving and emulating payment card NFC’s removed. I completely understand why this was removed from the OFW, but it would be nice to have added back in Unleashed. I understand the implications of this request, but please remember it can already be done just by flashing an older version of the firmware.

**Comment by ankris812** [comment]
you can only emulate uid, thats not enough to emulate a card, so its a useless feature, it was removed to save space, because it did nothing

**Comment by xMasterX** [comment]
Flipper was never been able to emulate full EMV card, this feature was UID emulation which is useless (you can't clone your payment card), only might be useful if you using bank card as access card to office, but its very very rare case
So, for what usage you need saving and UID emulation of bank cards?

**Comment by xMasterX** [comment]
UID Emulation and saving function is back, might be useful with some access control system that uses EMV cards as access cards
But if reader uses EMV for auth it will not work at all!
