### ISSUE TITLE
Extension of the NFC reading distance

### ISSUE THREAD

**Issue by d4rkduck1** [DarkFlippers/unleashed-firmware#126]
### Description of the feature you're suggesting.

It would be really great to be able to extend the NFC reading range, by plugging a D-Logic reader into the Flipper.

https://www.d-logic.com/nfc-rfid-reader-sdk/products/ufr-xl-oem/
or
https://www.d-logic.com/nfc-rfid-reader-sdk/products/dl533n-xl-nfc-reader-oem/

Example:
Instead of having to stick a badge directly on the Flipper to read it, we could have the external reader hidden in a shoulder bag, connected to the Flipper with a cable (more or less long). 
Let's say it could be more discreet and practical during pentests, to get information on badges, just by taking the elevator with employees for example. Much more discreet than having to place Flipper on their card haha

### Anything else?

![image](https://user-images.githubusercontent.com/73966315/197322184-37dd55d0-3af2-4e29-a200-0b5298b773ce.png)

**Comment by xMasterX** [comment]
You can't do that due to hardware limitations, also flipper can't be USB Host
