### ISSUE TITLE
App connection 

### ISSUE THREAD

**Issue by Chaoscake** [DarkFlippers/unleashed-firmware#127]
### Describe the enhancement you're suggesting.

Currently the apps on phones won't work with Unleshed.
I liked the option to have the flipper in my pocket and starting a SubGHz attack from my phone.

Can you make it work?

### Anything else?

THANK YOU

**Comment by xMasterX** [comment]
> Currently the apps on phones won't work with Unleshed. 

This statement is wrong, provide error messages, screenshots, logs, what exactly doesn’t work

**Comment by Chaoscake** [comment]
Flipper App on Android won't work.Error message "Update firmware to use this feature"Am 22.10.22, 12:49 schrieb MX ***@***.***>:

   
   
   Currently the apps on phones won't work with Unleshed. 
   
  This statement is wrong, provide error messages, screenshots, logs, what exactly doesn’t work
