### ISSUE TITLE
unlshd-006 seems to have issues emulating NFC

### ISSUE THREAD

**Issue by vashmalachi** [DarkFlippers/unleashed-firmware#129]
### Describe the bug.

After updating to `unlshd-006`, I attempted to emulate an Amiibo file that was known to work and no device would read it. Tested with another Flipper on stock firmware and a Pixel 3. Both devices could read that tag before updating when emulated by my Unleashed Flipper. All saved NFC files seem affected.

### Reproduction

Update to `unlshd-006` using web updater.
Navigate to NFC > Saved > Any NFC file > Emulate.
Hold to NFC reader.
Get no output from reader, as if no tag was presented.

**Comment by xMasterX** [comment]
Tested with NTAG215, emulation works fine, send your "broken" file here
Looks like problem is on your side, or with that particular file

**Comment by vashmalachi** [comment]
I can send a few, if you'd like but they are just the ones from the amiibo db on the awesome flipper github. I also tried with some random saved NFCs that could be read before the update. After downgrading to the previous version it works again. Would you still like me to send some files?

**Comment by xMasterX** [comment]
send files that don’t work, or issue will be closed because bug can’t be reproduced

**Comment by vashmalachi** [comment]
To further clarify, it wasn't just one file. All files I tried to emulate failed to be read.

**Comment by vashmalachi** [comment]
Here are some that I tried:
[NFCs.zip](https://github.com/DarkFlippers/unleashed-firmware/files/9848391/NFCs.zip)

**Comment by xMasterX** [comment]
I tested your files, emulation works fine, so the problem on your side, and can’t be replicated

All files worked fine, can be read with proxmark and with smartphone
