### ISSUE TITLE
Frequency analyser shortcut in bruteforce app

### ISSUE THREAD

**Issue by BrunoKlu** [DarkFlippers/unleashed-firmware#131]
### Description of the feature you're suggesting.

When performing a subghz bruteforce attack it would be nice to have a shortcut that quickly enables frequency analysyser in case a target is comming, you can quickly switch to frequency analyser and know if you choose the right frequency for the bruteforce.

**Comment by xMasterX** [comment]
Frequency analyzer works in distances like 5-10cm 

not like 100 meters

So this is not possible

**Comment by BrunoKlu** [comment]
Ok completely agree thanks for feedback

**Comment by BrunoKlu** [comment]
By the way Is there any sources telling how the frequency analyser is working ?

**Comment by BrunoKlu** [comment]
Is it because the reciever sensivity is very bad compare to the transmitter output power ?

**Comment by xMasterX** [comment]
https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/main/subghz/helpers/subghz_frequency_analyzer_worker.c

**Comment by BrunoKlu** [comment]
Thanks 🙏
