### ISSUE TITLE
Favorites page

### ISSUE THREAD

**Issue by Zandja150** [DarkFlippers/unleashed-firmware#132]
### Description of the feature you're suggesting.

I was wondering about the possibility to have a favorites menu somewhere within the flipper to access things like ir,nfc,rfid, etc for the controlls that are set that a person may set that they use the most

**Comment by xMasterX** [comment]
Its already present in firmware for long time, in archive app (file browser) (down button on main screen)
select file, click Pin, it will be added to favourites
