### ISSUE TITLE
Sort files in browser feature

### ISSUE THREAD

**Issue by vivi7** [DarkFlippers/unleashed-firmware#133]
I have thousands of file in infrared folder for example by brand, but they are order random or by added date, I want to order alphabetically.

**Comment by FalsePhilosopher** [comment]
sudo fatsort -n /dev/sdb1

**Comment by xMasterX** [comment]
Also solution for Windows:

https://www.anerty.net/software/file/DriveSort/

**Comment by RogueMaster** [comment]
@xMasterX I have tested https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/389 to be working well

**Comment by Supertera** [comment]
This is not work with 128 Gb SD-card, cause it is formatted (by flipper) in exFAT file system. And fatsort don't work with it probably the same reason.

**Comment by Supertera** [comment]
My wish, about it... may be someone will adding sorting utility to the "application"

**Comment by RogueMaster** [comment]
> My wish, about it... may be someone will adding sorting utility to the "application"

Just build RogueMaster#389 into your FW

**Comment by Supertera** [comment]
> Just build [RogueMaster#389](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/389) into your FW

Awessome! Please, add this in the future release of unleashed firmware...

**Comment by j2shortt** [comment]
I have the same issue. I just use the qflipper software to create folders. Then standard organization by personal preference beyond that.

**Comment by xMasterX** [comment]
Now implemented in firmware
