### ISSUE TITLE
API Version Mismatch on APP_SentrySafe

### ISSUE THREAD

**Issue by docb117** [DarkFlippers/unleashed-firmware#135]
### Describe the bug.

When running the application App_SentrySafe an error is thrown:

Error: 
Preload Failed
API version Mismatch

### Reproduction

Switch on
Go to Applications
Run APPS_SentrySafe

**Comment by r1ddl3rz** [comment]
I have no problem with this application. 
Tested with fresh flashed version. Works well.
Maybe not clean flashed?

**Comment by xMasterX** [comment]
We don’t have any app with name starting from APP_
This is leftovers from your roguemaster installation, delete sdcard/apps folder and install unleashed again, all will be ok after that

**Comment by docb117** [comment]
xmaster is correct, i followed the instructions and all is well now
