### ISSUE TITLE
Add 330 MHz in setting_user

### ISSUE THREAD

**Issue by LowSkillDeveloper** [DarkFlippers/unleashed-firmware#136]
### Describe the enhancement you're suggesting.

Might be worth adding "Frequency: 330000000" to setting_user by default? On this frequency works same remote controls, various gates and barriers also used it. And if this frequency is added, the flipper can catch them and decode.

![Screenshot-20221026-225321](https://user-images.githubusercontent.com/25121341/198136857-ee486abc-7efb-45eb-9897-d6dd4f9a0462.png)

Or is there any reason for the absence of this frequency?

**Comment by portman56** [comment]
Can we not add it ourselfs? Edit the settings_user file?

**Comment by xMasterX** [comment]
Added to config and frequency analyzer, thanks!
