### ISSUE TITLE
Flipper crashes when you turn off the device while it is plugged in the usb

### ISSUE THREAD

**Issue by Blackn0va** [DarkFlippers/unleashed-firmware#142]
### Describe the bug.

If the Flipper is connected to the PC via USB and you turn off the Flipper, the Flipper crashes reproducibly.

### Reproduction

1. Plug in USB and Connect to PC
2. Power ON Flipper.
3. Power Off Flipper
4. Flipper Reboots and Crashed.

**Comment by xMasterX** [comment]
Fixed in release v012, please update and verify that all works fine now

**Comment by Blackn0va** [comment]
release v012 has fixed this issue. All Works fine.
