### ISSUE TITLE
Add EAN-8 to barcode generator.

### ISSUE THREAD

**Issue by NikitaKorneev** [DarkFlippers/unleashed-firmware#151]
### Description of the feature you're suggesting.

It would be rather nice to have EAN-8 as one of the first _other_ barcodes to be included in barcode generator. I know they are coming - just really desperate) 

<img width="150" alt="Screenshot 2022-11-06 at 12 54 23" src="https://user-images.githubusercontent.com/60179299/200164467-698ed185-b894-4dc3-93b3-07c2774d0348.png">

### Anything else?

Thank you for everything)

**Comment by xMasterX** [comment]
Support for EAN-8 added with PR #154 
PR already merged in dev and will be in next release
