### ISSUE TITLE
UniRF: Labels aren't picked up when not all signal files defined

### ISSUE THREAD

**Issue by vkulpa** [DarkFlippers/unleashed-firmware#153]
### Describe the bug.

I have a `some_remote.txt` file in the `unirf` folder with the following content
```
UP: /ext/subghz/someSignal.sub
ULABEL: SomeLabel
```
Label in the unirf app will be `someSignal` instead of `SomeLabel`

As a solution I think we could just rewind stream before looking up the labels.
![image](https://user-images.githubusercontent.com/883900/200298575-c0f2fcd1-a384-4882-9730-73ef89cec0e8.png)

### Reproduction

1. Create a txt file in unirf folder with only UP and ULABEL properties defined
2. Open Sub-Ghz remote app
3. Select the remote
4. ULABEL isn't taken UP filename will be used instead

**Comment by xMasterX** [comment]
Fixed in dev, will be included in next release, thanks for report
