### ISSUE TITLE
Rename application HC-SR04

### ISSUE THREAD

**Issue by krolchonok** [DarkFlippers/unleashed-firmware#158]
### Describe the enhancement you're suggesting.

All GPIO applications have square brackets in the name. The HS-SR04 Dist. Sensor has no brackets(

How it looks now:
![Screenshot-20221108-225248](https://user-images.githubusercontent.com/40743392/200663495-dc47d2b9-4381-4759-b451-06c3c7283685.png)

How it should look like:
![Screenshot-20221108-225927](https://user-images.githubusercontent.com/40743392/200663625-6d49ea11-4cee-4289-a545-37255a9bcee1.png)

### Anything else?

thank you for your work

**Comment by suculent** [comment]
The plugin was successfully tested with HC-SR05/HY-SRF05. Maybe [HC-SR] Dist. Sensor would be sufficient.

**Comment by xMasterX** [comment]
Resolved in PR #161 
Thanks
