### ISSUE TITLE
Incorrect link in "how to" for Temperature Sensor Plugin.

### ISSUE THREAD

**Issue by gid9798** [DarkFlippers/unleashed-firmware#159]
### Describe the enhancement you're suggesting.

Two incorrect links.

first in the Community apps included section.
[second](https://github.com/DarkFlippers/unleashed-firmware#--how-to-use-temperature-sensor-plugin---htu21d--si7021)

new link https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/plugins/htu21d_temp_sensor/Readme.md

**Comment by xMasterX** [comment]
Thanks, links are fixed now
