### ISSUE TITLE
Unleashed-014 Installation - Manifest Error

### ISSUE THREAD

**Issue by Soulsender** [DarkFlippers/unleashed-firmware#160]
When trying to update from version 13 to version 14, error message is logged:

```
[UTL] Start Update @Urs4ku ERROR: Manifest folder not found
[DEV] Full Update @Urs4ku ERROR: Manifest folder not found
```

at which point it refuses to continue.

Tried on both linux and windows.

**Comment by xMasterX** [comment]
your problem is not related to firmware
