### ISSUE TITLE
value_index in .fap "Error Load failed. Found unsatisfied imports"

### ISSUE THREAD

**Issue by hrundeel** [DarkFlippers/unleashed-firmware#162]
Thanks, but this don't help. 
Building is ok (without any errors/warnings now), but after uploading .fap to "Sd Card/Misc" and trying to run - it not work with message "Error Load failed. Found unsatisfied imports".
Don't know how to do.

_Originally posted by @hrundeel in https://github.com/DarkFlippers/unleashed-firmware/issues/155#issuecomment-1309872391_

**Comment by xMasterX** [comment]
Read my reply in older issue
