### ISSUE TITLE
Wav player crashes

### ISSUE THREAD

**Issue by MopishFungus** [DarkFlippers/unleashed-firmware#165]
### Describe the bug.

Tried playing a wav file on the flipper and it crashed. [WAV HERE](https://easyupload.io/9lfbuw)

### Reproduction

1. Downloaded newest firmware.
2. Turned on
3. Navigated to wav player
4. Selected my wav file
5. Crashed and kicked out of wav player

### Target

WAV player

**Comment by xMasterX** [comment]
**Let’s read instructions together, they say:**

<img width="681" alt="Screenshot 2022-11-15 at 04 04 06" src="https://user-images.githubusercontent.com/10697207/201800965-f332e923-46a5-4d00-a7c5-a54059e0a479.png">


**Now let’s look at your file:**


<img width="281" alt="Screenshot 2022-11-15 at 04 05 10" src="https://user-images.githubusercontent.com/10697207/201801053-15d3d938-2ebd-4fc3-924f-a520f104f150.png">


Do you see a problem with your file? If you don’t, then read instructions again
Your file was not converted to proper format that wav player accepts
