### ISSUE TITLE
Sleep mode as clock

### ISSUE THREAD

**Issue by LY2NEO** [DarkFlippers/unleashed-firmware#168]
### Description of the feature you're suggesting.

After some time if device are not in use, activate clock app.

**Comment by MNeroba** [comment]
+1

**Comment by LY2NEO** [comment]
I change my mind and think that better to have always clock on main screen ;)
Already made code with working clock on main screen, basically it works, but still needs a few fixes...

![image](https://user-images.githubusercontent.com/118531425/205465268-e9909558-6610-437d-93f4-de5931428398.png)
