### ISSUE TITLE
Flipper name doesn't change

### ISSUE THREAD

**Issue by ghost** [DarkFlippers/unleashed-firmware#177]
### Describe the bug.

I tried changing the flipper name to my liking and based on the specifications described in name.txt, but when I boot the device the name stays the same.

I see that in the "What's Changed" section it says 'Customizable Flipper name', but it doesn't work. Coming from the RogueMaster fork, by changing the name it worked.

### Reproduction

1. Edit "name.txt" file by navigating to ext/dolphin/name.txt
2. Erase what's after the "Name: " and replace with "Name: TEST0123"
3. Save, unmount and insert card back to flipper. Boot and check.

### Target

unlshd-015 Latest

**Comment by xMasterX** [comment]
Read manual 

https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/CustomFlipperName.md

If you want some Roguemaster functionality here you are in wrong repo
