### ISSUE TITLE
Hold up for dummy mode instead of lock

### ISSUE THREAD

**Issue by PharoahCoder** [DarkFlippers/unleashed-firmware#179]
### Description of the feature you're suggesting.

Hold up while in desktop for dummy mode instead of lock

**Comment by oliva** [comment]
I think this would work best if exiting dummy mode also required entering the password

**Comment by PharoahCoder** [comment]
> I think this would work best if exiting dummy mode also required entering the password

Oh yeah and an option that disables password prompting for exiting dummy mode so you just enter the password combination and it unlocks without asking for password so it looks like a toy.

**Comment by Leptopt1los** [comment]
It is not planned. Blocking is used much more often than transition in dummy mode
