### ISSUE TITLE
NFC Mifare DESfire 

### ISSUE THREAD

**Issue by vilewired** [DarkFlippers/unleashed-firmware#182]
### Describe the bug.

I scanned a friend's NFC tag today (it unlocks a door) and I was able to save it without any problems. When I tried to access it though it prompted me with a 'file couldn't be parsed' error. Later today when I was home I connected my flipper to my pc and took a look at the .nfc file. The Device Type was Mifare DESfire. I didn't see a problem with the file itself or the contents, so I asked in the help section of the Flipper Zero Unofficial Discord. A guy called miga screwed a bit around with the information I gave him and he figured out that if you change your device type to DESfire Mifare on any .nfc file it brings up the same error. So I am not sure if it is intended to be that way or if simply I made a mistake and him only editing the Device Type made his file corrupt but I just wanted to let you know to see if this is a bug or not.

### Reproduction

1. Turn on the Flipper
2. Head to the NFC tab
3. Select Read
4. Read a NFC tag (Mifare DESfire)
5. Save the tag
6. Access the tag through the 'saved menu
7. Upon opening the saved .nfc file you should get prompted with: 'File can not be parsed'
8. You can analyze the file itself aswell.

### Target

NFC - Mifare DESfire

### Logs

```Text
The screenshot of my .nfc file:

https://cdn.discordapp.com/attachments/978425715525582918/1045349033742434405/image.png
```

**Comment by xMasterX** [comment]
Try again with latest release
