### ISSUE TITLE
QR (and other barcodes) from text files

### ISSUE THREAD

**Issue by sliceratwork** [DarkFlippers/unleashed-firmware#185]
### Description of the feature you're suggesting.

It would be interesting if the Flipper could generate QR codes or other types of barcodes, from text files uploaded on the SD card.

Because of the Flipper's screen size, I know the maximum size a QR code can have is 64x64px, so not too much data, but here are other types of barcodes that could prove useful.

As an added bonus, pressing the left/right arrows would cycle through the different text files in a folder, updating the QR code. Another option would be to have a "playlist file"  with a list of file names/code payloads,  where every X seconds the Flipper jumps to the next QR code.
 

### Anything else?

References:
https://github.com/h0nus/QRGen
https://null-byte.wonderhowto.com/how-to/create-malicious-qr-codes-hack-phones-other-scanners-0197416/

**Comment by xMasterX** [comment]
Implemented here - https://github.com/bmatcuk/flipperzero-qrcode

Build also can be downloaded here - https://github.com/xMasterX/unleashed-extra-pack
