### ISSUE TITLE
Frequency Analyzer in 016

### ISSUE THREAD

**Issue by H3rrOberst** [DarkFlippers/unleashed-firmware#189]
### Describe the bug.

The Sub-GHZ frequency analyzer no longer recognizes my key since updating on FW 016

Car Key BMW Raw 433.92 Mhz

Switched back to FW015 and it worked again. 

### Reproduction

Scan in Frequency Analyzer

### Target

SubGhz Frequency Analyzer

**Comment by xMasterX** [comment]
Flipper has no support for car keys, RAW recording wasn’t changed between updates at all

**Comment by H3rrOberst** [comment]
The problem is only in the frequency analyzer not read the raw. It just surprised me because it works in 015
