### ISSUE TITLE
Sub-Ghz Universal remote

### ISSUE THREAD

**Issue by PharoahCoder** [DarkFlippers/unleashed-firmware#190]
### Description of the feature you're suggesting.

Hi,

Has anyone thought of creating a universal remote just like the infrared but for sub-ghz frequencies for things like restaurant pagers and gates/barriers. each device type can have a group to access the universal remote for it for example infrared has acs, tvs, projectors. Sub-ghz universal remote can have a barriers section, pager section and so on. Maybe even an option specifically for restaurant pagers that allows the restaurant id to be bruteforced. I really think this would be a good addition to the firmware.
I would do this myself but my experience with C is very limited.
Let me know what you guys think.

Inspiration:
[Xenobyte's creation of the t119 bruteforcer](https://twitter.com/xenobyte_/status/1554222170888339456?lang=en)

Contact me at  ak@yousefak.com for any questions
PS: For educational purposes

**Comment by askoriy** [comment]
I think it's not possible. Unlike TVs and ACs that have the same and well-known codes for the model, every gate or restaurant pager has its own code, that could be found only by sniffing or bruteforce.

**Comment by RocketGod-git** [comment]
This feature already exists.

![Screenshot-20221128-084408](https://user-images.githubusercontent.com/57732082/204334543-34cad880-856d-415f-a6b3-a085905aa4cd.png)
![Screenshot-20221128-084448](https://user-images.githubusercontent.com/57732082/204334545-7c24470f-556f-48d8-98f1-a4a22407b931.png)
![Screenshot-20221128-084543](https://user-images.githubusercontent.com/57732082/204334549-b64b5994-c4c7-4b78-be7d-787cb506eebc.png)

**Comment by PharoahCoder** [comment]
> I think it's not possible. Unlike TVs and ACs that have the same and well-known codes for the model, every gate or restaurant pager has its own code, that could be found only by sniffing or bruteforce.

Thats why im suggesting there should be a built in bruteforce mode for each brand that doesnt require exporting analyzing and manually creating raw bruteforce sub files.

**Comment by PharoahCoder** [comment]
> This feature already exists.
> 
> ![Screenshot-20221128-084408](https://user-images.githubusercontent.com/57732082/204334543-34cad880-856d-415f-a6b3-a085905aa4cd.png) ![Screenshot-20221128-084448](https://user-images.githubusercontent.com/57732082/204334545-7c24470f-556f-48d8-98f1-a4a22407b931.png) ![Screenshot-20221128-084543](https://user-images.githubusercontent.com/57732082/204334549-b64b5994-c4c7-4b78-be7d-787cb506eebc.png)

I meant something to bruteforce though. Also that doesn't work for me it says "please configure map" even though they are already there.

**Comment by RocketGod-git** [comment]
You can use whatever .sub files you want.
Read the readme to learn how to make your own map files.

**Comment by PharoahCoder** [comment]
> You can use whatever .sub files you want. Read the readme to learn how to make your own map files.

Yeah but that means you cant do it straight from the flipper without emulating it. You would have to listen then export it to create a bruteforced version. A better way would be to bruteforce straight from the device with preconfigured files just like the acs.ir and fans.ir

**Comment by kurbus** [comment]
> Thats why im suggesting there should be a built in bruteforce mode for each brand that doesnt require exporting analyzing and manually creating raw bruteforce sub files.

Each brand of TV? Sometimes not even the same TV manufacturer uses the same frequencies.

**Comment by xMasterX** [comment]
> > This feature already exists.
> > ![Screenshot-20221128-084408](https://user-images.githubusercontent.com/57732082/204334543-34cad880-856d-415f-a6b3-a085905aa4cd.png) ![Screenshot-20221128-084448](https://user-images.githubusercontent.com/57732082/204334545-7c24470f-556f-48d8-98f1-a4a22407b931.png) ![Screenshot-20221128-084543](https://user-images.githubusercontent.com/57732082/204334549-b64b5994-c4c7-4b78-be7d-787cb506eebc.png)
> 
> I meant something to bruteforce though. Also that doesn't work for me it says "please configure map" even though they are already there.

https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/SubGHzRemotePlugin.md
