### ISSUE TITLE
sd card databases

### ISSUE THREAD

**Issue by JackTheFine** [DarkFlippers/unleashed-firmware#199]
### Describe the bug.

whenever i try anything it says i need new databases but idk where to get them for unleashed

### Reproduction

click infared then universal then try to use buttons

**Comment by xMasterX** [comment]
Read instructions how to install firmware, you did something wrong or your micro sd is faulty 

https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/HowToInstall.md
