### ISSUE TITLE
Enable SubGhz TestStatic & TestPacket Debug modes

### ISSUE THREAD

**Issue by jonschoning** [DarkFlippers/unleashed-firmware#210]
### Describe the enhancement you're suggesting.

in Commit https://github.com/DarkFlippers/unleashed-firmware/commit/3c1efda1dbf0f5ff6fa97f837390291a3b5d808e SubGhz TestStatic & TestPacket Debug modes are excluded.  

Is there a reason why these debug modes should be excluded in compilation and not made available when the user selects Debug mode from the settings menu?  They seem like useful tests to have available

**Comment by xMasterX** [comment]
They are not excluded, build firmware with DEBUG=1
they are not present in release firmware to save some space
