### ISSUE TITLE
Applications like WAV Player and DTMF don't work

### ISSUE THREAD

**Issue by ahumeniy** [DarkFlippers/unleashed-firmware#221]
### Describe the bug.

A change in OFW breaks apps which access the internal speaker. Apps using `furi_hal_speaker_*` seem to be fixed already, but other apps like WAV Player and DTMF uses a different method for accessing the speaker and don't produce sound anymore.

### Reproduction

Open Wav Player, try to play an audio file.
Nothing is heard.

**Comment by gid9798** [comment]
You are probably using unlshd-021 firmware. If so, please upgrade to unlshd-022 and the problem should disappear.

**Comment by xMasterX** [comment]
Fixed in release 022
