### ISSUE TITLE
[NFC] unlshd-022 firmware EMV read/save/emulate problem

### ISSUE THREAD

**Issue by ghost** [DarkFlippers/unleashed-firmware#226]
### Describe the bug.

Since I have updated to unlshd-022 I noticed I am unable to utilize any newly saved EMV cards.
I am getting the error message "Can't parse data from app" when reading a card. After saving, the .NFC file seems okay, but then there is the error message "Can not parse file" when I try to emulate it/run it in app.
Problem is consistent for any kind of EMV type card I tried. Even those read and emulated before successfully. Proper reading, saving and trying to emulate them now does not work.
Although all the cards saved previously are good for use.

### Reproduction

1. Open NFC>Read
2. Read EMV card. > Displays error message "Can't parse data from app".
3. Save card.
4. Select NFC>Saved>[saved card] and Run in app. > Displays error message "Can not parse file".

**Comment by xMasterX** [comment]
I tried with couple different emv cards, all works fine, issue can not be replicated via described steps

also you can't emulate emv, you can emulate only uid, to use with some access control systems
