### ISSUE TITLE
2048 game

### ISSUE THREAD

**Issue by eugene-kirzhanov** [DarkFlippers/unleashed-firmware#228]
### Describe the enhancement you're suggesting.

Hi everyone.
Can I suggest to add yet another game for Flipper Zero to Unleashed Firmware?
https://github.com/eugene-kirzhanov/flipper-zero-2048-game

**Comment by xMasterX** [comment]
Yes, since you are author, do you want to make a PR with this game added to plugins, or you want me to add it by myself?

**Comment by eugene-kirzhanov** [comment]
> Yes, since you are author, do you want to make a PR with this game added to plugins, or you want me to add it by myself?

Thanks for the answer. I'll try to add PR. If I fail, I will ask for help.

**Comment by xMasterX** [comment]
Sure
