### ISSUE TITLE
Mismatch api (clock and RFID_Fuzzer)

### ISSUE THREAD

**Issue by Robskee123** [DarkFlippers/unleashed-firmware#231]
### Describe the bug.

Might be me doing something wrong, long time lurker and first time poster, no real coding experience.

The clock and RFID fuzzer are displayed as question mark and giving an api version mismatch.

![flpr-2022-12-22-03_41_40](https://user-images.githubusercontent.com/121208948/209044436-b7713241-3fe5-4de9-b71d-9e003c3814c9.png)
![flpr-2022-12-22-03_42_21](https://user-images.githubusercontent.com/121208948/209044490-92846b10-c5bf-4c5d-9f3f-62a5e6e5f61f.png)
![flpr-2022-12-22-03_42_30](https://user-images.githubusercontent.com/121208948/209044498-991e0c77-08fd-4ff3-8acb-f7bfd6903448.png)

### Reproduction

1. Application
2. Misc -> RFID fuzzer
3. Tools -> clock 

### Anything else?

After updating to 022 (flipper-z-f7-update-unlshd-022)

**Comment by xMasterX** [comment]
Yes you are doing something wrong, our firmware has no Clock in apps

And RFID fuzzer is located in Tools, not in Misc

You copied that files manually and they was compiled on older API
