### ISSUE TITLE
Option to NOT remove TX Region Restrictions.

### ISSUE THREAD

**Issue by yodaluca23** [DarkFlippers/unleashed-firmware#241]
### Describe the enhancement you're suggesting.

Option to NOT remove TX Region Restrictions maybe something like what [Rouge Master](https://github.com/RogueMaster/flipperzero-firmware-wPlugins) Has...

### Anything else?

I would really like to use Unleashed, but I don't want to worry about accidentally/mistakenly using frequencies restricted from consumers...

**Comment by xMasterX** [comment]
Why? Do you have basic understanding about TX power that flipper has?
I don't see any reason to lock frequencies in custom firmware, use official one if you don’t feel comfortable with region unlock

**Comment by mantacid** [comment]
maybe not removing them, but making the user confirm the use of a frequency that would normally be region-locked would be a good idea.

**Comment by grantgarbe** [comment]
This would be an amazing addition. It scares me that I could be doing illegal things, so I'm using the official software. I would switch back to Unleashed if this is added.
