### ISSUE TITLE
Morse Code will crash flipper firmware

### ISSUE THREAD

**Issue by ryanthomp** [DarkFlippers/unleashed-firmware#248]
### Describe the bug.

Still an issue with 022, flipper will crash after an extended use of the Morse Code tool. Sometimes freezing the flipper other times just rebooting flipper firmware. 

### Reproduction

After using morse code app, it will freeze stop producing characters but still making noise then after it will either stop working or crash the firmware, I will add logs later once I download them from the flipper.

**Comment by ryanthomp** [comment]
Furi-check fails, could see anything in the debug logs

**Comment by xMasterX** [comment]
Fixed in #249
