### ISSUE TITLE
Incorrect config for Sub-GHz Remote

### ISSUE THREAD

**Issue by fluxxion82** [DarkFlippers/unleashed-firmware#259]
### Describe the bug.

sub-ghz config map example(`unirf_map_example`) is incorrect

### Reproduction

Fresh install of latest unleashed firmware: UNLSHD-023e
Navigate to Sub-GHz Remote
try to load "unirf_map_example"

result:
![sub_ghz_incorrect_config](https://user-images.githubusercontent.com/2243087/210450021-0ccdfb59-6e4c-4a8c-9690-390d33fb5a32.png)

### Anything else?

after installing the firmware, I just continued to click the center button and the FW crashed with some null reference message. I think the screen before the crash was pointing to a github and had an 'ok' button at the botton, but instead of clicking right for 'ok', i clicked the center button.

**Comment by bunk3r** [comment]
Please, take a look at https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/SubGHzRemotePlugin.md

**Comment by fluxxion82** [comment]
Ah ok.  it might be less confusing to not even have the example file, which isn't configured, so I go to the documentation first to figure out how to setup a UniRF map, but i guess it can be said that one should read the manual first. anyways, thanks for the pointer to the doc.
