### ISSUE TITLE
Using saved IR remotes freezes the device.

### ISSUE THREAD

**Issue by avinal** [DarkFlippers/unleashed-firmware#260]
### Describe the bug.

When a saved IR remote is used. The led keeps blinking and the device freezes often.

### Reproduction

1. Go to the menu
2. Open Infrared
3. Choose the saved remote
4. Open a remote
5. Emulate a saved key
6. Observe  

### Target

Infrared

**Comment by fastnlight0** [comment]
Same issue here. Only fix is to restart flipper. Hopefully unleashed fixes this soon

**Comment by xMasterX** [comment]
Bug cannot be reproduced, provide more details, your remote files, and firmware version
