### ISSUE TITLE
Auto Lock functionality

### ISSUE THREAD

**Issue by MMVipper** [DarkFlippers/unleashed-firmware#266]
### Description of the feature you're suggesting.

autolock can we have a way to have it "Lock With Pin" ? auto after 10-15-20-30-90sec?

**Comment by H3rrOberst** [comment]
Go to Settings->Desktop->Auto-lock Time

**Comment by MMVipper** [comment]
> Go to Settings->Desktop->Auto-lock Time

@H3rrOberst 

That is the auto lock without the pit, its the lock where you have to press back 3x times, i want autolock with pin

**Comment by Salamafet** [comment]
For your information, even if your Flipper is locked, it can be restarted with left and back button. 
When the Flipper start, the screen is unlocked by default.

The lock function is not a function for protecting the Flipper against thief or other joker (it can be easily reset). This function prevents the Flipper to make anything when it is in your pocket.
The pin locking it's against child, I suppose.

**Comment by xMasterX** [comment]
> ### Description of the feature you're suggesting.
> autolock can we have a way to have it "Lock With Pin" ? auto after 10-15-20-30-90sec?
> 
> ### Anything else?
> _No response_

Please read @Salamafet response
His message describes all my thoughts about this, auto lock with pin is useless because it can be easily reset with two buttons, we had that function in the past, and it was removed because of that

**Comment by ClaraCrazy** [comment]
Sorry to just join in on that like that but why does your FW not lock after a (re)boot?
