### ISSUE TITLE
NRF24 Sniffer screen blanking, doesn't find or log any signals.

### ISSUE THREAD

**Issue by VinnyTheLegend** [DarkFlippers/unleashed-firmware#271]
### Describe the bug.

Screen blanks before swapping to next channel sometimes. Never any found or unique signals. NRF24 Scanner app seems to work just fine, but unfortunately as far as I can figure out the saved addresses are not compatible with the mousejacker app, and I don't have the experience to convert them.

### Reproduction

1. Generate compatible 2.4gz signal.
2. Run the NRF24 Sniffer for a reasonable amount of time.
3. Notice the screen blanking on channel swap frequently (but not every time).
4. Fail to find any signals.
5. Confirm signal presence with the NRF24 Scanner app.

**Comment by xMasterX** [comment]
Screen blanking is fine, app works in one thread, it can be optimised by rewriting it to mutlithread, but as you can see its still hasn’t been done

Also nrf scanner app is detecting all traffic, while nrf sniffer looks for specific traffic that can be used with mousejacker
If you didn’t found anything that doesn’t mean app is not working, that can mean that you tested it with not vulnerable hardware, you need to look for vulnerable hardware list before trying
