### ISSUE TITLE
Region Information submenu

### ISSUE THREAD

**Issue by OperKH** [DarkFlippers/unleashed-firmware#275]
### Describe the bug.

In commit  2c450bd835dffa18dfa6662d658c3f75079e9b92 there was added Sub-GHz submenu "Region Information" but it had been deleted during merge.

It's quite cool to see what region originaly provisioned on your Flipper.

![Region Information submenu](https://gcdnb.pbrd.co/images/GfOYpCZh4j0M.png)
![Region Information scene](https://gcdnb.pbrd.co/images/5hIqXUxdRmEK.png)

### Reproduction

1. Open Sub-GHz
2. There should be "Region Information" going below "Frequency Analyzer"

**Comment by xMasterX** [comment]
We don't have provision system, it is removed and functions replaced with mocks
This menu will not work, and also you can see your region info in flipper mobile app in developer settings
Hardware region is shown up on about screens correctly
