### ISSUE TITLE
Battery display type is not refreshed

### ISSUE THREAD

**Issue by alvarotorijano** [DarkFlippers/unleashed-firmware#276]
### Describe the bug.

If you change the battery display style it will not be apllied upon the next reboot.
This seems to be working on the official firmware as they said je je je https://github.com/flipperdevices/flipperzero-firmware/issues/2268#event-8176907582applied

### Reproduction

Go to: Settings -> desktop -> (wait) -> battery view
Return to the desktop.

**Comment by amec0e** [comment]
This is normal behaviour when changing the battery icon, this feature is NOT in official firmware either so not sure why you would message them about custom firmware features.

A simple reboot of your flipper after changing the battery indicator is all that is needed to fix this issue which isn't really a issue as far as I can see.

**Comment by xMasterX** [comment]
Its made like that because we have no ability to refresh current battery drawing from other place (settings app in this case)
Also this is not a bug, it just implemented like that, it could be updated in the future
