### ISSUE TITLE
Pocsag pager settings file 

### ISSUE THREAD

**Issue by aero-oli** [DarkFlippers/unleashed-firmware#277]
### Describe the bug.

when using the settings file to edit frequencies nothing changes despite following the described procedure. i.e stuck with the default frequencies, settings file for pocsag doesn't appear to work .

### Reproduction

load settings file into /ext/pocsag/settings.txt

**Comment by aero-oli** [comment]
anyone got this to work?

**Comment by devBioS** [comment]
make sure the folder is named pocsag (with c) and the file is settings.txt.

Just tested and works for me
