### ISSUE TITLE
Stripe pixels missing

### ISSUE THREAD

**Issue by BreezeDog420** [DarkFlippers/unleashed-firmware#279]
### Describe the bug.

After installing unleashed firmware onto latest flipper store update, a stripe of pixels is missing down the left side of screen. Still able to see and function. I had to install newest release then reinstall unleashed.

### Reproduction

Don't know, I'm not a programmer.

**Comment by xMasterX** [comment]
Looks like your screen is defective, install official firmware and contact official flipper support
