### ISSUE TITLE
Minesweeper Game

### ISSUE THREAD

**Issue by mikhatech** [DarkFlippers/unleashed-firmware#281]
### Describe the bug.

mines are never generated in the first row and column!

### Reproduction

Go to application; games; Minesweeper; start game

**Comment by gid9798** [comment]
Not really, mines are not generated in the row and column of the first click.
![image](https://user-images.githubusercontent.com/30450294/211613546-b039a8b6-7675-428f-bf88-36e95e06ea1f.png)
![image](https://user-images.githubusercontent.com/30450294/211613643-bcd64f42-e60d-48f0-8f3f-77c6dddfbdfe.png)
![image](https://user-images.githubusercontent.com/30450294/211613698-35470e70-8385-44e5-8977-efe2aa620f77.png)
FW: dev237

**Comment by TQMatvey** [comment]
@mikhatech This isnt our application, it is taken from [this](https://github.com/panki27/minesweeper) repo, you can mirror the issue there
