### ISSUE TITLE
BadUSB backspace/delete fix

### ISSUE THREAD

**Issue by erachen** [DarkFlippers/unleashed-firmware#286]
### Describe the bug.

As described in flipperdevices/flipperzero-firmware issue 2220,
the `DELETE` key is really the `BACKSPACE` key and the real `DELETE` key is missing.

https://github.com/flipperdevices/flipperzero-firmware/issues/2220
Is it possible to integrate this fix in unleashed too ?
cf:
https://github.com/flipperdevices/flipperzero-firmware/pull/2288

### Reproduction

1. create a simple badusb script: `simple-del.txt` with this:
```
DELAY 1000
DELETE
```
2. play this badusb script on a computer
3. check what key is send (for example `xev` on linux) and see it is really `BACKSPACE`

**Comment by xMasterX** [comment]
Yes all changes will be synced, just wait
