### ISSUE TITLE
Missing folders for unlshd-024 during "clean" install

### ISSUE THREAD

**Issue by Fasjeit** [DarkFlippers/unleashed-firmware#295]
### Describe the bug.

Installing `unlshd-024` with formatted SD card cause some folders missing making some default apps non-operational.

Windows 10, official qFlipper, tgz update.

 SD card after installing `unlshd-023n` (everything is fine):
![img](https://user-images.githubusercontent.com/15075638/213399000-8ccd9d9a-0cc7-4330-93d7-9622abe11851.png)

 SD card after installing `unlshd-024n`:
![img](https://user-images.githubusercontent.com/15075638/213399089-04444da5-8f61-4acb-b8f0-9a6ee7aca1f0.png)

SubHz error after clean install (`unlshd-024n`):
![img](https://user-images.githubusercontent.com/15075638/213399732-b9c89eaa-88d2-4a2f-9ffe-fd3a4c5d00b4.png)

### Reproduction

1. Format SD card in flipper
2. Install `flipper-z-f7-update-unlshd-024n.tgz` with qFlipper (windows)
3. Go to SD card /
4. Some required folders (like `subghz`) are missing

**Comment by xMasterX** [comment]
Looks like qflipper didn’t installed it correctly or you have a faulty microsd

Build is fine and all folders are present, nothing was changed or broken in process

<img width="403" alt="Screenshot 2023-01-19 at 14 20 27" src="https://user-images.githubusercontent.com/10697207/213429682-cc4c56c3-80eb-435b-a889-928c5e430268.png">

**Comment by Fasjeit** [comment]
Yes, I can confirm the folders are present in tgz, but I still can reproduce this behavior using 24, but not 23 or official firmware, which is really weird...

**Comment by xMasterX** [comment]
> Yes, I can confirm the folders are present in tgz, but I still can reproduce this behavior using 24, but not 23 or official firmware, which is really weird...

Problem present only with no custom animations `n` build?

**Comment by Fasjeit** [comment]
Same behavior for all versions. 

But seems installing 2 versions sequentially actually works (first install `n` then `e` version).

I'll double check with flipper mobile app update.

ps. A little off topic here: it looks like there are some strange folders located in apps (cannot be open or deleted). Is it an expected behavior? 
![img](https://user-images.githubusercontent.com/15075638/213435975-c2f75b63-86d9-45c0-9ae3-eb12915b56f3.png)
![img](https://user-images.githubusercontent.com/15075638/213436041-04f99f60-48f1-40d9-99f9-ac92b31c6504.png)

**Comment by Fasjeit** [comment]
Same behavior with flipper mobile app.

**Comment by xMasterX** [comment]
> ps. A little off topic here: it looks like there are some strange folders located in apps (cannot be open or deleted). Is it an expected behavior?

No, this is not expected behaviour and its more and more looks like something wrong with file system or microsd

Can you try with other microsd?

**Comment by Fasjeit** [comment]
Yep, SD card was the reason. Really weird.... All the problems are gone with a new one.

Thank you!
