### ISSUE TITLE
Crashing when scanning Sub-Ghz with Hopping and RAW detection

### ISSUE THREAD

**Issue by ghost** [DarkFlippers/unleashed-firmware#296]
### Describe the bug.

Crashing when scanning Sub-Ghz with Hopping and RAW detection on any modulation except AM270 and AM650

### Reproduction

1.Switch on
2.Go to Sub-Ghz
3.Go to Read
4.Go to Config
5.Select Modulation FM238 or any but AM
6.Set Hopping - ON
7.Set Detect Raw - ON
8.Press BACK

Crashing after less that 1 minute

### Target

Sub-Ghz

**Comment by xMasterX** [comment]
<img width="924" alt="Screenshot 2023-01-19 at 16 15 07" src="https://user-images.githubusercontent.com/10697207/213452292-57d0187a-1527-490a-8b5b-8638baa0dd67.png">

**Comment by xMasterX** [comment]
https://github.com/DarkFlippers/unleashed-firmware/commit/5853e0bdd9c7ef76ac9ed9bb05b262bf9fc5b374
