### ISSUE TITLE
RFID Fuzzer. Delay After send.

### ISSUE THREAD

**Issue by lmsecure** [DarkFlippers/unleashed-firmware#301]
### Description of the feature you're suggesting.

**Description of the problem**: Some readers not answer, if we send requests without delay. 
**Solution**: Now there is a setting in seconds, how long to send the code. You need to add a delay after the code is sent. The delay must be configured in seconds. The setting must be done through the interface using the up and down buttons.

**Comment by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [comment]
Why not use ms instead?

**Comment by xMasterX** [comment]
Has been done in latest version
