### ISSUE TITLE
The NFC keys file inside the firmware contains invalid data

### ISSUE THREAD

**Issue by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [DarkFlippers/unleashed-firmware#304]
### Describe the bug.

 File nfc/mf_classic_dict.nfc contains some keys with invalid data (not hex)

Some characters should not be there, for examlpe: O,L,Q which is not allowed in hexadecimal alphabet[0-9,A-F]
A lot of apps may work incorrect with these keys because their alphabet stuck on this key lines.

### Reproduction

1. Open file mf_classic_dict.nfc
2. Remove hexadecamal characters in lines without '#'
3. You will see a lot of trash characters

### Target

keys

### Logs

```Text
/nfc/mf_classic_dict.nfc:3735: E64Q986Q5D94 (Q)
/nfc/mf_classic_dict.nfc:3735: E64Q986Q5D94
/nfc/mf_classic_dict.nfc:3587: D53732OFF9OE (not Zero)
/nfc/mf_classic_dict.nfc:3587: D53732OFF9OE
/nfc/mf_classic_dict.nfc:3597: EDOEC56EEFDD
/nfc/mf_classic_dict.nfc:3612: 2E52ABEOCE95
/nfc/mf_classic_dict.nfc:3614: 61DO30COD7A8
/nfc/mf_classic_dict.nfc:3614: 61DO30COD7A8
/nfc/mf_classic_dict.nfc:3586: EL67EC67C7FF (L)
/nfc/mf_classic_dict.nfc:3592: 36EL765CE3E8
/nfc/mf_classic_dict.nfc:3595: C608EL3ADD50
/nfc/mf_classic_dict.nfc:3598: 9716D524LE28
/nfc/mf_classic_dict.nfc:3733: 4ADLE273EAFL
/nfc/mf_classic_dict.nfc:3733: 4ADLE273EAFL
/nfc/mf_classic_dict.nfc:3734: 3DFL4C8000A1
```

### Anything else?

It is easy to fix just to sort lines contains only regex [0-9] and [a-f]
Some L may be replaced to 1
Some O to 0
Some Q to O

**Comment by xMasterX** [comment]
Resolved in `f45f2a45da80a00aa5e949b204539fdbb0913fd3`

I cleaned up those keys, they came from unknown origin and may be dynamic which means they are useless and just slows down process
