### ISSUE TITLE
No release log (build manifest) gets displayed on the Flipper Mobile app during the upgrade process

### ISSUE THREAD

**Issue by AdilusPrimus** [DarkFlippers/unleashed-firmware#314]
![image](https://user-images.githubusercontent.com/3187466/216844510-5d34ad97-d9db-47c4-8b61-79d8eab35e4e.png)

There is a section serving that purpose, how can we publish the Release log in it?
I guess for the next version since  I think that this would require a new build.
If aligned accordingly would be happy to contribute.
Thanks!

**Comment by ea1nk** [comment]
Similar issue with web updater and qFlipper trying [flipper-z-f7-update-unlshd-026e.tgz](https://github.com/DarkFlippers/unleashed-firmware/releases/download/unlshd-026/flipper-z-f7-update-unlshd-026e.tgz)
[RPC] (7) System Update @/ext/update/f7-update-unlshd-026e/update.fuf START
[UTL] Start Update @******** ERROR: Manifest folder not found
[DEV] Full Update @******** ERROR: Manifest folder not found

**Comment by xMasterX** [comment]
Change log in app is parsed from official update server, not from .tgz archive
Our firmware is not official and app shows empty page
