### ISSUE TITLE
Hold middle button to change animation on desktop only works with DEBUG mode enabled

### ISSUE THREAD

**Issue by ms4sman** [DarkFlippers/unleashed-firmware#315]
### Describe the bug.

I recently noticed I suddenly couldn't hold the middle button while on the desktop to change the animation anymore. 
I tried to think through my recent changes and one that came to mind was that I had disabled DEBUG mode in the settings as I didn't think I needed it on at the moment as I'm not debugging anything.

I went to the settings and turned it back on, and now it works fine.

Is this intended behavior, or perhaps this feature can only work with DEBUG turned on due to a hardware limitation or something, or is this just a bug that can be easily fixed?

Thanks for all the hard work on this project!

### Reproduction

In Settings, under System, turn DEBUG mode to off.
Hit back until you are back at the "desktop"
Try pressing and holding the middle button, which should change the animation. It doesn't anymore.

**Comment by xMasterX** [comment]
this is not a bug, thats how it intended to be, i made this to be like that
