### ISSUE TITLE
028  - crashing when sending over ext

### ISSUE THREAD

**Issue by p1337** [DarkFlippers/unleashed-firmware#331]
### Describe the bug.

When sending recorded signals 028 crashes, while ext is enabled.
downgraded to 027 - works just fine. 

maybe "subghz hal" fixes are causing this ?

### Reproduction

1. Enable EXT in sub ghz. 
2. Record signal 
3. Send recorded signal 
4. Crash 

"Flipper crashed and was rebooted"
"NULL pointer dereference"

**Comment by xMasterX** [comment]
Fixed in latest release
https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-029
