### ISSUE TITLE
028 | Crashing when opening large folders

### ISSUE THREAD

**Issue by Milk-Cool** [DarkFlippers/unleashed-firmware#332]
### Describe the bug.

If a folder contatins a lot of files, the flipper will crash when you open it in the file browser ("furi_check failed"). This happened after the introduction new feature where the files are alphabetically sorted. Video: https://youtu.be/ChRX6iaUVbU

### Reproduction

1. Get a folder with a lot of files
2. In the file browser, open that folder

### Target

Flipper Zero FZ.1

**Comment by xMasterX** [comment]
Fixed in latest release
https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-029
