### ISSUE TITLE
Does Barcode Generator support Code39/Code128?

### ISSUE THREAD

**Issue by griffonlee** [DarkFlippers/unleashed-firmware#339]
### Description of the feature you're suggesting.

[code39_encodings.txt](https://github.com/DarkFlippers/unleashed-firmware/files/10741583/code39_encodings.txt)
[code128_encodings.txt](https://github.com/DarkFlippers/unleashed-firmware/files/10741586/code128_encodings.txt)

**Comment by xMasterX** [comment]
No, app included with firmware does not support that
App in extra pack does
