### ISSUE TITLE
Bluetooth BadUSB Feature

### ISSUE THREAD

**Issue by Gacut** [DarkFlippers/unleashed-firmware#341]
It would be cool to get this feature from the video adapted into Unleashed firmware: 
[Link to Youtube Video](https://www.youtube.com/watch?v=lh99ssUy6FE)

Someone mentioned already that Bluetooth is not fully used it's potential on flipper zero so it could be a good start.

**Comment by ClaraCrazy** [comment]
If people could wait, please? Its already been mentioned on the discord multiple times now.

I wrote this... my team wrote this. People instantly run to devs asking them to pull out ctrl-c ctrl-v. Theres an agreement to get it to unleashed eventually once it is bugfree and running fine, and once we had stable exclusivety of it for one version. 

Patience is a virtue

**Comment by Gacut** [comment]
No need to be hostile about that. Not everyone is on every single discord server. I didn't see any mentions about this in here so i thought maybe this will start some kind of colaboration between devs.

Simple "It's in the works" would be enough.
Thanks for the info tho and sorry for asking.

**Comment by ClaraCrazy** [comment]
After seeing other people take work without crediting, an estimated 3 seconds after release, my sympathy for people asking to integrate features from us is gone. Also, a collaboration, without involving me into the conversation by using a ping? Thats for you for next time, ping them. Looks like a silent `sweeping under the rug` otherwise. 

Having said that, sorry for the shitty response. Like i said, you can go say thanks to the "devs" that cant follow codex. Have a great day.

**Comment by mayday77** [comment]
unf unf

**Comment by Gacut** [comment]
> After seeing other people take work without crediting, an estimated 3 seconds after release, my sympathy for people asking to integrate features from us is gone. Also, a collaboration, without involving me into the conversation by using a ping? Thats for you for next time, ping them. Looks like a silent sweeping under the rug otherwise.
Having said that, sorry for the shitty response. Like i said, you can go say thanks to the "devs" that cant follow codex. Have a great day.

No hard feelings. And yeah, getting a credit in internet is a bitch. Have a nice day aswell :)

**Comment by kimusan** [comment]
@ClaraCrazy what discord server is that? Would be nice to be able to follow such conversations. 
On a side note: I am fully for the whole "move to unleased eventually" agreement, but do remember that you have released FlipperExtreme under GPL3 license and shared the code publicly so there is nothing preventing people from copying it fully legally and use it in their non-commercial projects.

**Comment by ClaraCrazy** [comment]
there is. and nano / xMasterX knows that :) 

and the server is on my repo
