### ISSUE TITLE
Misc_Extra>Barcode, missing encoding table.

### ISSUE THREAD

**Issue by griffonlee** [DarkFlippers/unleashed-firmware#342]
### Describe the bug.

When loading a barcode created by "CODE-39" or "CODE-128", the error message "Missing encoding table" appears.

### Reproduction

1. Go to Applications> Misc_Extra> Barcode.
2. Create Barcode with Type "CODE-39" or "CODE-128", then save it.
3. Load the barcode that created from step2.

**Comment by xMasterX** [comment]
1 - Wrong repo
2 - Open correct repo, find link to this app, open that link
3 - Read manual, download missing files, try again
