### ISSUE TITLE
BadUSB Bluetooth option

### ISSUE THREAD

**Issue by ghost** [DarkFlippers/unleashed-firmware#346]
### Description of the feature you're suggesting.

https://www.youtube.com/watch?v=lh99ssUy6FE

Wireless BadUSB with Flipper Zero's Inbuilt Bluetooth!

**Comment by ClaraCrazy** [comment]
negative.

**Comment by BBoyzthehacker** [comment]
why not clara?

**Comment by Louis-Beke** [comment]
Hello,
Thanks for your email.
We will answer you when posible.
Best,
LSystemus Team

**Comment by Nothankyou111** [comment]
Seriously lady what is your problem? Stop being a bitch

**Comment by ezpzX1** [comment]
who where you talking to me or clara

**Comment by ezpzX1** [comment]
why where you talkin to? them or clara

**Comment by Nothankyou111** [comment]
Clara

**Comment by ghost** [comment]
Oh sad

**Comment by ClaraCrazy** [comment]
I wasnt serious, dw. Just love triggering kids. 

As mentioned on both our discord and the unleashed discord, it will be merged once its stable

**Comment by BBoyzthehacker** [comment]
nice!

**Comment by Louis-Beke** [comment]
Hello,
Thanks for your email.
We will answer you if possible.
Best,
LSystemus team

**Comment by Nothankyou111** [comment]
> I wasnt serious, dw. Just love triggering kids.
> 
> As mentioned on both our discord and the unleashed discord, it will be merged once its stable

Just love being a cunt, ehh?

**Comment by ClaraCrazy** [comment]
hell yea

**Comment by BBoyzthehacker** [comment]
same tbh clara also when u gon update xtream it been 3 weeks

**Comment by alexl83** [comment]
May I suggest to call it “BadBlues” when it gets launched in UNLSHD?

**Comment by ghost** [comment]
yes

**Comment by xMasterX** [comment]
done
