### ISSUE TITLE
Avalanche transceiver

### ISSUE THREAD

**Issue by azaitsev** [DarkFlippers/unleashed-firmware#347]
### Description of the feature you're suggesting.

Can flipper work on 457Mhz?
https://en.wikipedia.org/wiki/Avalanche_transceiver

**Comment by xMasterX** [comment]
> ### Description of the feature you're suggesting.
> Can flipper work on 457Mhz? https://en.wikipedia.org/wiki/Avalanche_transceiver
> 
> ### Anything else?
> _No response_

Wiki says 457 kHz not MHz
and flipper can't work on 457khz
only with external module
