### ISSUE TITLE
Change to external antenne in CLI mode

### ISSUE THREAD

**Issue by ready63** [DarkFlippers/unleashed-firmware#348]
### Description of the feature you're suggesting.

Can I change to external antenne in CLI mode?
It is possible change modulation type in CLI mode?

**Comment by xMasterX** [comment]
why?

**Comment by ready63** [comment]
For increase range when I logging instancens with Flipper

**Comment by xMasterX** [comment]
> For increase range when I logging instancens with Flipper

Set it to external using GUI, then you can close app and use CLI
It will remember its state until reboot

**Comment by ready63** [comment]
Thanks!
