### ISSUE TITLE
bad usb

### ISSUE THREAD

**Issue by BBoyzthehacker** [DarkFlippers/unleashed-firmware#350]
### Describe the enhancement you're suggesting.

can you please add the bad usb bluetooth thats in xtream? i have been running xtream for that one reson. if you add it i will use this frimware.

BTWWWWW im 11 years old so please dont be mean about it if you cant!!!! (:

**Comment by ClaraCrazy** [comment]
negative

**Comment by xMasterX** [comment]
Stop spamming with duplicate issues
