### ISSUE TITLE
Sub ghz not working with key fob

### ISSUE THREAD

**Issue by Hammes50** [DarkFlippers/unleashed-firmware#355]
Initially after recording and then sending it worked but after saving and then trying it won't work. I tried a bunch of configurations, still won't work. I tried analyzing it came up 312.099, but won't record it that high, it will only record 303. something but will do nothing when I press send. I'm new to this, I did a bunch of research,  I generally understand a good amount, but what can I do to get this to record key fob to a 2004 pontiac GTO? The key fob is almost dead and will be impossible to get a new one or even replace the battery,  GM made sure to make it this way.  Please help me figure this out, thank you. I hope this is in the right thread this time.

**Comment by xMasterX** [comment]
Car keys is not supported and will not be supported in our firmware, if you create issue about car keys again you will be banned

If your keyfob is dying you need to buy replacement, flipper is not an car opener
