### ISSUE TITLE
Battery charging issue

### ISSUE THREAD

**Issue by Milkmik83** [DarkFlippers/unleashed-firmware#356]
### Describe the bug.

![ChargeIssue](https://user-images.githubusercontent.com/121310844/220318988-5a8ea1c8-f9a8-458e-85a4-e9103df5448f.png)
Version 030. Trying to charge Flipper when battery residual charge is 12% but the LED that usually was turning red while charging stays OFF.
It is not a cable issue since in Settings -> Power -> Battery Info it show that battery is already charged.

### Reproduction

With version 030 installed try to charge the battery

**Comment by Milkmik83** [comment]
![ChargeOK020](https://user-images.githubusercontent.com/121310844/220322015-1e7d6841-f8a1-46cd-8b46-002f42e8aafc.png)
I've downgrade the FW to 022 to charge the battery.

**Comment by xMasterX** [comment]
Issue can't be replicated, also no one reported any issues with charging, also nothing was changed in power management code

Looks like you having hardware issues
