### ISSUE TITLE
Infrared keyboard

### ISSUE THREAD

**Issue by f-mns** [DarkFlippers/unleashed-firmware#361]
### Describe the bug.

When I try to save a new remote(button) the keyboard letters are capital so they should write capital letters right? But when I type it's small. When I save the remote and remove the example text, it's an capital letter. 

https://user-images.githubusercontent.com/78693466/220982738-d44c584e-dedc-4f19-a739-1bee48f82256.mp4

Also normaly when theres a keyboard left from the save button theres a `_`. when it's an capiltal keyboard it also shows "_" but writes an space like when you longpress the `_` in normal mode. 
The funny thing is when theres an example text and the keyboard should write capital letters the `_` wents to an ` ` but also writes `_`.

https://user-images.githubusercontent.com/78693466/220982717-1112adf8-8d0c-47c2-a37b-3f2d50c5dfcd.mp4

### Reproduction

Described above

**Comment by ClaraCrazy** [comment]
I'm curious, can you replicate this anywhere else? I remember having had such an issue on my Firmware too, but I eventually fixed it. I'm on a trip right now but if you can confirm this to be present everywhere (mainly wherever there is a sample text to replace) I know its my old issue and I can PR a fix once im back home

**Comment by f-mns** [comment]
I tried it on SubGHz and theres the same problem.

**Comment by ClaraCrazy** [comment]
Good enough for me. I'll PR a fix in the coming days. 

Or actually… @Willy-JL can you do that? Remember when I did that tiny change on the keyboard input.c? That's what's needed here.

**Comment by WillyJL** [comment]
Will do :ok_hand:
