### ISSUE TITLE
BadUSB won't detect connection and/or hangs

### ISSUE THREAD

**Issue by rf-bandit** [DarkFlippers/unleashed-firmware#365]
### Describe the bug.

BadUSB will behave normally if 

1) script is selected and run, then connected to target computer, or,
2) connected to target computer then run.

Running the same script multiple times from the launch screen works as expected. Backing out to the selection script menu the attempting to run a second time/different script will  a hang on "will run on connect". Backing out to main menu and relaunching BadUSB app will cause script to run normal; unplugging and replugging usb cable to target at this stage causes a hang that needs to be rebooted.

### Reproduction

Open BadUSB, connect to target, and run script.
Back out to select script menu, and re-run script -- will hang on "will run on connect". 
Unplug USB from target and reconnect
FZ will freeze and require reboot

### Anything else?

Bug present on 30 and 31

**Comment by xMasterX** [comment]
Fixed in dev branch
