### ISSUE TITLE
Parsel`s counter

### ISSUE THREAD

**Issue by ready63** [DarkFlippers/unleashed-firmware#368]
### Describe the enhancement you're suggesting.

In many cases, such a feature would be useful. Can I add it?

**Comment by xMasterX** [comment]
It’s named Cnt: in every rolling protocol supported by flipper

**Comment by ready63** [comment]
Perhaps I expressed myself inaccurately: we are talking about the number of identical parcels

**Comment by xMasterX** [comment]
same parcel being sent all time you holding the button like on original remotes
