### ISSUE TITLE
Recent Count range check break secplus_v2 keys

### ISSUE THREAD

**Issue by AndrewPGA** [DarkFlippers/unleashed-firmware#370]
### Describe the bug.

https://github.com/DarkFlippers/unleashed-firmware/blob/172c0e077fcae840c1f87c5c0f02f9109f379886/lib/subghz/protocols/secplus_v2.c#L382
Commit 172c0e077fcae840c1f87c5c0f02f9109f379886 set the upper key range to 0xFFFF, which might break current keys. Rolling code for secplus_v2 is 28 bits, therefore the max value should be 0xFFFFFFF (2^28). 
Tested on a chamberlain garage door opener, after enroll a key w/ rolling code 0xFFFE, the opener accepted the key once (0xFFFF), and does not accept the next one (0x0)

### Reproduction

enroll a key w/ rolling code 0xFFFE on a chamberlain garage door opener , the opener accepted the key once (0xFFFF), and does not accept the next one (0x0) and after

### Anything else?

Did not test other protocols that made the same change in that commit.

**Comment by xMasterX** [comment]
Fixed, thanks for report
