### ISSUE TITLE
mousejacker (null pointer dereference)

### ISSUE THREAD

**Issue by smannchen** [DarkFlippers/unleashed-firmware#371]
### Describe the bug.

The mousejacker app crashes with null pointer dereference upon trying to open a ducky script.

### Reproduction

1. open mousejacker
2.  try to load script
3.  crash

### Target

unlshd-033e, and xtreme firmware

**Comment by xMasterX** [comment]
> ### Describe the bug.
> The mousejacker app crashes with null pointer dereference upon trying to open a ducky script.
> 
> ### Reproduction
> 1. open mousejacker
> 2. try to load script
> 3. crash
> 
> ### Target
> unlshd-033e, and xtreme firmware
> 
> ### Logs
> _No response_
> 
> ### Anything else?
> _No response_

Do you have NRF24 connected and you have parsed and working address obtained via NRF24 Sniffer app (not from extra pack) in `addresses.txt` file that you need to select first after launching mousejacker?

**Comment by smannchen** [comment]
The addresses txt is present with one valid address. It very well can be
user error lol. Could it be the SD card?

**Comment by RogueMaster** [comment]
Where is your addresses.txt? Was it generated by NRFSniffer app?

**Comment by smannchen** [comment]
I did use the sniffer app. captured a logitech address. I verified it is being saved to the addresses.txt. oddly after deleting the file and running sniffer again it seems to work. I figured it might no be a software issue, and probably a failing SD card.

**Comment by xMasterX** [comment]
> I did use the sniffer app. captured a logitech address. I verified it is being saved to the addresses.txt. oddly after deleting the file and running sniffer again it seems to work. I figured it might no be a software issue, and probably a failing SD card.

I'm closing this issue then
