### ISSUE TITLE
Infrared - Learn New Remote Issue 

### ISSUE THREAD

**Issue by m5performance** [DarkFlippers/unleashed-firmware#377]
### Describe the bug.

When trying to learn new remote Flipper zero is picking up random IR Signals even if no external IR remote is being pressed or external signal is sent.

### Reproduction

To replicate the issue:

1- Go to Infrared app.
2- Select either Learn New Remote or Learn New Remote Raw.
3- as soon as you select one of the two options mentioned above almost immediately random signals start to get picked up.

### Target

Latest Build

**Comment by xMasterX** [comment]
this is not an firmware issue, ir receiver is too sensitive, put it in a dark place, it pickups noises from your lamps 
we can make it blind by turning sensetivity lower, thats not a good solution

**Comment by m5performance** [comment]
Got it, makes sense. Thank you for clarifying this. Also wanted to thank you for your work and contributions to this firmware. You legend!
