### ISSUE TITLE
TOTP Locking Up Flipper

### ISSUE THREAD

**Issue by lwrcase** [DarkFlippers/unleashed-firmware#379]
### Describe the bug.

Flipper is freezing up whenever a modal appears on the TOTP application.

- Entering incorrect pin
- Deleting a token
- Using "incorrect" secret for a new token.

The only way to recover is to press left & back.

### Reproduction

1. Enter incorrect PIN on TOTP application
2. Try to delete a token.
3. Try to set an "invalid" secret for a token.

### Target

TOTP Authenticator

**Comment by xMasterX** [comment]
TOTP was updated, please verify on latest UL dev build or download .fap here
https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.6.5

Issue can't be reproduced on latest version

**Comment by lwrcase** [comment]
Confirmed tested and issue is gone. Thank you!
