### ISSUE TITLE
Lora Breakout board support

### ISSUE THREAD

**Issue by Spessmen14** [DarkFlippers/unleashed-firmware#383]
### Description of the feature you're suggesting.

The hard work has already been done, source code available at 

https://github.com/aafksab/LORA-Term

Adding this would enable the Flipper to access these breakout board.

**Comment by xMasterX** [comment]
Already present in Extra pack

**Comment by EvanCarroll** [comment]
I would love to know why the breakout board is even needed. The c1101 supports 915mhz and there are c1101 implementations of LoRa gateways. It would seem to me like you should be able to get _some_ kind of functionality with the stock antenna and c1101.

**Comment by RogueMaster** [comment]
Ok Evan, make it happen 😃
