### ISSUE TITLE
OpenHaystack support

### ISSUE THREAD

**Issue by lcd1232** [DarkFlippers/unleashed-firmware#388]
### Description of the feature you're suggesting.

Integrate OpenHaystack into the firmware so you can find it if it was stolen

### Anything else?

Here is old implementation of it - https://github.com/AlexStrNik/flipperzero-firmware

**Comment by pdostal** [comment]
That would be super cool!

**Comment by smannchen** [comment]
The GitHub link seems broken :(

**Comment by supaeasy** [comment]
Yes please!

**Comment by xMasterX** [comment]
Was done here: https://github.com/MatthewKuKanich/FindMyFlipper

And now included in base pack, that means app is present in default builds and extra apps builds
Apps->Bluetooth->Find my
