### ISSUE TITLE
Minesweeper - Freezes device

### ISSUE THREAD

**Issue by Aronanbo** [DarkFlippers/unleashed-firmware#389]
### Describe the bug.

When playing if a mine is hit it will freeze on the game screen or will freeze on the game over screen no buttons will work. device is new no other files added.
sandisk 32gb ultra sd card 
Latest stock firmware installed.
then installed Unleashed with additional apps
hardware 12.f7b9c6

running 036e

### Reproduction

just standard playing game when mine is hit it crashes device

**Comment by xMasterX** [comment]
Fixed in dev branch, install latest dev build
