### ISSUE TITLE
Application Sub-GHz BruteForcer

### ISSUE THREAD

**Issue by dybman** [DarkFlippers/unleashed-firmware#390]
### Describe the bug.

The brute force function for CAME 12Bit 868.35MHz does not work at all.

### Reproduction

I tested even recording a frame on the zero flipper away from the gate to avoid the rolling code barrier. The flipper does not work at all to replay a code for Came 12bit 868.35MHz.

**Comment by xMasterX** [comment]
Learn basics of digital radio and what rolling code is, before creating such issues

**Comment by xMasterX** [comment]
Learn basics of digital radio and what rolling code is, before creating such issues

**Comment by Ismaje7791** [comment]
Wow 🤟

**Comment by dybman** [comment]
Silly answer from a person who is obviously self-sufficient.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Ismaje7791 ***@***.***>
Date : 09/05/2023 17:01 (GMT+01:00)
À : DarkFlippers/unleashed-firmware ***@***.***>
Cc : dybman ***@***.***>, Author ***@***.***>
Objet : Re: [DarkFlippers/unleashed-firmware] Application Sub-GHz BruteForcer (Issue #390)


Wow 🤟
