### ISSUE TITLE
The WAV player does not work

### ISSUE THREAD

**Issue by MythicalCodingLabs** [DarkFlippers/unleashed-firmware#397]
### Describe the bug.

When I upload a file using [Flipper Lab](lab.flipper.net) and tried to open it the WAV player just closes. Is this a bug or am i just having this problem.

-Note
I tried to put the WAV file in the music player folder and when i opened it the entire flipper just crashed and rebooted

### Reproduction

1 Add attached file to WAV player folder
2 On your flipper open WAV player
3 Open the file

When you try to open it the screen just flashes and goes back to the files page
[File](https://drive.google.com/file/d/1-YRLYV52WhH18LAmSzCAv5OdJ9dpZxJC/view?usp=sharing)

### Logs

```Text
1666526 [I][LoaderSrv] Starting: Applications
1666532 [I][AnimationManager] Unload animation 'L1_Senpai_128x64'
1666554 [D][BrowserWorker] Start
1666561 [D][BrowserWorker] Enter folder: /ext/apps items: 6 idx: -1
1666563 [D][BrowserWorker] Load offset: 0 cnt: 50
1670821 [D][BrowserWorker] Enter folder: /ext/apps/Media items: 4 idx: -1
1670824 [D][BrowserWorker] Load offset: 0 cnt: 50
1673381 [D][BrowserWorker] End
1673393 [I][FapLoader] FAP Loader is loading /ext/apps/Media/WAV_Player.fap
1673435 [I][FapLoader] FAP Loader is mapping
1673562 [I][elf] Total size of loaded sections: 5424
1673566 [I][FapLoader] Loaded in 173ms
1673568 [I][FapLoader] FAP Loader is starting app
1673584 [D][BrowserWorker] Start
1673593 [D][BrowserWorker] Enter folder: /ext/wav_player items: 1 idx: -1
1673596 [D][BrowserWorker] Load offset: 0 cnt: 50
1676399 [D][BrowserWorker] End
1676413 [E][WavParser] WAV: non-PCM format 1, next '536885140'
1676433 [I][FapLoader] FAP app returned: 0
1676441 [D][BrowserWorker] Start
1676456 [D][BrowserWorker] Enter folder: /ext/apps/Media items: 4 idx: 2
1676458 [D][BrowserWorker] Load offset: 0 cnt: 50
1680512 [D][BtGap] set_non_discoverable success
```

**Comment by xMasterX** [comment]
[fix_01.wav.zip](https://github.com/DarkFlippers/unleashed-firmware/files/11064455/fix_01.wav.zip)

Don't use online converters
Your file was in incorrect format
