### ISSUE TITLE
Picopass app not reading elite keyed cards anymore.

### ISSUE THREAD

**Issue by Akury83** [DarkFlippers/unleashed-firmware#413]
Hi all,

I just upgraded from ver 034 to ver 042 and I’ve found that the picopass app no longer reads elite keyed cards, even ones keyed with the keys in dictionary files. The old version of the app used to read elite keyed cards with the default or icopy-x keys..

Any help would be greatly appreciated with this one, cheers!

**Comment by Akury83** [comment]
Hello all, tested with the new firmware: 043, still not working…

**Comment by xMasterX** [comment]
Can you tell more details? We are not making this plugin, it came from OFW and made by @ bettse 
What you doing to read it?
App has added new menu option, to read elite cards, do you using it or trying default read?

**Comment by Akury83** [comment]
Ohh I see, I had no idea it was just pulled from the OFW.. Thanks for letting me know.

In the old version, it would read standard or elite keyed cards with the one read option.

In the new version, it reads standard cards with the regular read option, but doesn’t read elite keyed cards using the ‘Elite dict attack’ option, even after going through the dictionary of available keys.

Considering this is pulled from the OFW, should I close this request and raise the request there?

**Comment by xMasterX** [comment]
Correct, also better to try it by installing latest OFW dev build first, to make sure issue still present
Also, You tried both read and elite dict options on that card? 
None of them worked?

**Comment by Akury83** [comment]
Tried the latex OFW, and OFW dev build, both failed to read an elite coded card using both elite and elite dict options. The card is coded in the standard key, but with the elite algorithm. Thanks for your help, I’ll close this and raise in the official channels.
