### ISSUE TITLE
Internal Storage Blockage on self-built .dfu Installation

### ISSUE THREAD

**Issue by lesterrry** [DarkFlippers/unleashed-firmware#414]
## What I am trying to do:
- Clone this repo
- Run `./fbt`
- Install the built .dfu file via qFlipper

## What I expect:
- Firmware being flashed and installed on the device with no further issues

## What I get:
- Firmware being flashed and installed on the device 
- 0 KiB free displayed in _About Internal Storage_ tab in device settings
- No adjustments to device's settings (e.g. adding pin code) may be made (they just won't get applied)
- To restore the internal storage repairing the device is required through qFlipper, installing in the process default (not unleashed) release version of firmware

## What I've also tried:
- Updating via Updater Package from SD Card
- Updating via built .tgz file

## What I will not try:
- Update via Web Updater or any other way through pre-built releases. I am **specifically** looking to build the firmware myself

## Important notes:
- This hasn't always been like this. I've been using this same method for months with no such issues. If I recall correctly, the problems began somewhere around [unlshd-031](https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-031) version
- This issue does not exist if I do the same process but with official firmware
- MacOS 10.15.7
- qFlipper 1.3.0

**Comment by xMasterX** [comment]
Why do you using debug builds then? build release

`./fbt updater_package COMPACT=1 DEBUG=0`

or if you need debug build for development use this `./fbt FIRMWARE_APP_SET=debug_pack updater_package`
if this still doesnt work, i will check what can be excluded, since we hit memory size limits with debug build

also when you flashing only .dfu file you will end up with half of apps not working, use .tgz package generated by `fbt` in dist folder, flash it using qflipper, it allows that

**Comment by lesterrry** [comment]
> Why do you using debug builds then? build release

I do need debug build for development, so I used the instructions given in ['How to build'](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/HowToBuild.md). 

Building debug version with `./fbt FIRMWARE_APP_SET=debug_pack updater_package` did work. Thank you! 


As simple `./fbt` command given in ['How to build'](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/HowToBuild.md) does not work, I suggest you update the documentation on building the firmware according to this issue. I will create a PR with updates soon.

**Comment by xMasterX** [comment]
Docs updated, thanks for information
