### ISSUE TITLE
Getting stuck in walls playing Doom

### ISSUE THREAD

**Issue by trigat** [DarkFlippers/unleashed-firmware#422]
### Describe the bug.

I'm not sure if I should post this here or in another Doom repository.  I updated my firmware to Unleashed yesterday and I notice I always get stuck in the walls when playing Doom.  Is this something that can be looked at?  It happens any time I touch the walls.

### Reproduction

Play Doom and run into walls.

**Comment by xMasterX** [comment]
Good find, this bug is almost year old, I have no time to fix it, and no one reported it since then
Fixing DOOM is lowest priority for me, since its not a proper game, its more like a demo, and it works good as a demo
Ill return to this when i have some time

**Comment by trigat** [comment]
Good to know.  Thank you.
