### ISSUE TITLE
control bug

### ISSUE THREAD

**Issue by Antonzab75** [DarkFlippers/unleashed-firmware#423]
good afternoon, after updating to the latest firmware 043, a bug appeared, after connecting through the application on android, the center button stops working, it only works in the settings menu and then only when you go there and then it doesn’t work, reboot helps, but then the bug appears spontaneously  , did not determine the regularity.

**Comment by xMasterX** [comment]
Known issue, 043 marked as prerelease, i published message in our discord and telegram channels where im say to wait for next release

Wait for 044 all will be fixed
