### ISSUE TITLE
Airmouse app

### ISSUE THREAD

**Issue by gui28347** [DarkFlippers/unleashed-firmware#430]
### Describe the enhancement you're suggesting.

Can you replace airmouse app that you have currently in the firmware that comes with extra apps with the one from: https://github.com/ginkage/FlippAirMouse/releases/tag/v0.0.4

Not sure the difference in code, but I believe some PINs are different. 

Using the version that comes with unleashed and the pcb of air mouse provided in https://github.com/ginkage/FlippAirMouse/releases/tag/v0.0.4 does not work correctly the mouse cursor is stuck in side.

Using the original version from their GITHub works perfectly.

My suggestion if possible is use that firmware, considering you can also find the PCBoard in github as well.

**Comment by xMasterX** [comment]
This is not correct, nothing different from that version and our build, compare by yourself using git diff or any other diff software

You will find that our build has different name in manifest, and thats all
