### ISSUE TITLE
Read RAW not correctly replaying

### ISSUE THREAD

**Issue by Jadelutis** [DarkFlippers/unleashed-firmware#431]
Hello, I've been having an issue with the replay functionality of the Read Raw menu. When  I first turn on the flipper it works just fine, I can read the raw signal and then replay it. But after the first time if I either erase the recorded signal and recapture, or back out of the menu and recapture, when I try to replay it, it just sits at the transmitting animation but does not send anything and sits at that screen forever. If I restart the flipper and do it again, it works fine for one time again. Please let me know if anyone else has this issue and if there is any resolution for it.

**Comment by xMasterX** [comment]
Already fixed in dev branch
