### ISSUE TITLE
Port "USB-UART Bridge" function from stock

### ISSUE THREAD

**Issue by dracode** [DarkFlippers/unleashed-firmware#442]
### Description of the feature you're suggesting.

In the stock firmware, you can go to GPIO -> USB-UART Bridge to use the Flipper as a serial adapter for a computer.

I don't see this tool in Unleashed, but it is useful. Is there a reason it is removed? Or is it present and just hiding in a different place?

**Comment by xMasterX** [comment]
What?

Nothing was removed or moved to other place, check again
