### ISSUE TITLE
BadKB (Wireless BadUSB)

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [DarkFlippers/unleashed-firmware#446]
### Description of the feature you're suggesting.

You guys should add Wireless BadUSB that Xtreme Firnware has. It will be a game changer. Thanks.

**Comment by xMasterX** [comment]
stop spamming duplicate issues

**Comment by EasyAntiCheatSoftware** [comment]
Oh sorry. I didn’t know other people request this issue. My bad
