### ISSUE TITLE
Cant change dolphin with debug off

### ISSUE THREAD

**Issue by Paco688** [DarkFlippers/unleashed-firmware#456]
### Describe the bug.

Typically your dolphin scene can be changed pubpressing and holding the ok button, I've noticed if you turn debug off, which is requried to use new deep sleep mode, you cant change the dolphin anymore

### Reproduction

Press and hold ok with debug off and dolphin doesn't change

**Comment by assasinfil** [comment]
Not a bug. The screen changes automatically.
