### ISSUE TITLE
Stealth mode should disable vibration motor & led

### ISSUE THREAD

**Issue by alexl83** [DarkFlippers/unleashed-firmware#459]
### Describe the enhancement you're suggesting.

I think it could be useful to disable all kind of obvious outputs in stealth mode
Silencing sound is great, and I think disabling vibration & led would enhance the functionality

While running covert, vibration sound or led blinking could more or less easily give away some activity and raise suspicion

### Anything else?

Whishlist-level suggestion
Thank you for your consideration - thank you for this great job with unleashed firware

**Comment by alexl83** [comment]
UPDATE: checked subghz READ and subghz "frequency analyzer" - Stealth mode disables vibration already, still unsure about behaviour in other apps - led blinking still active

tested on UNLSHD-48 release
Thank you

**Comment by xMasterX** [comment]
Stealth mode disables vibro and sound as it should
