### ISSUE TITLE
Feature Request:  "Relay" app - Listening event to trigger an action

### ISSUE THREAD

**Issue by tagraf** [DarkFlippers/unleashed-firmware#463]
### Description of the feature you're suggesting.

The Relay app is a powerful tool that can be used for a variety of purposes. Once opened, the app will display three tabs: Create, Saved, and About.

The Create tab is where you can create new relay conditions. To do this, select the IF row and choose a sub-system, file, or other object to listen for a signal. Once the signal is triggered, the THEN row will execute the selected action. You can also save your relay conditions for later use.

The Relay app has many potential uses. For example, you can use it to create a security monitor, a notification system, or even a prank. For example, you could set up the app to play a song when you press a certain button on your remote or open your garage door when you press a button on your TV remote.

**Comment by Leptopt1los** [comment]
Creating such an application will require the integration of many subsystems in it. An application of this size is unlikely to fit into the flipper's RAM. Reduced implementations of such functionality are possible, but we will provide the opportunity to implement them for the community
