### ISSUE TITLE
Lock and auto lock PIN not working

### ISSUE THREAD

**Issue by ghost** [DarkFlippers/unleashed-firmware#468]
### Describe the bug.

If PIN is set Flipper is not aaking for it after being locked manually. Also it gets stuck on the "To unlock tap..." screen after an auto lock if the auto lock PIN setting is turned on.

### Reproduction

1. Set up PIN.
2. Lock Flipper manually. OR Let Flipper do an auto lock.
5. Press Back button 3 times to try unlock Flipper.

**Comment by xMasterX** [comment]
PIN functionality was fully changed in dev branch and will be in next release
Im closing this since its already fixed in dev
