### ISSUE TITLE
Security+2.0 remote not working

### ISSUE THREAD

**Issue by victor-s-yip** [DarkFlippers/unleashed-firmware#469]
### Describe the bug.

On a craftsman overhead garage door, the flipper can register rolling security+2.0 at 310 Mhz and 390 Mhz. When using the registered code, the garage unit indicator appears to blink as if it read something but will not open or close. Running 048e. Existing remote still works and unpairs/repairs successfully. Garage door unit has myQ and is connected to the internet.

### Reproduction

1) Make a new security+2.0 rolling code remote at 310/390Mhz
2) Activate "learning" on unit
3) continuous transmit until receiver blinks confirmed (as per manual)
4) Try to transmit again to open/close door.

**Comment by xMasterX** [comment]
So, we need to find and buy a receiver like yours, get it on another side of our planet, in different continent?
Or how you think we should even try to replicate this "issue" ?
Maybe you can provide your original remote captures at least? It reads via "Read" mode or not?

**Comment by victor-s-yip** [comment]
Sorry about that. I was not sure if this issue was more widespread because it was referenced elsewhere without resolution. The original remote is recognized as a security+2.0 at 390Mhz. Would a normal read or a raw read be preferred for this?

**Comment by xMasterX** [comment]
> Sorry about that. I was not sure if this issue was more widespread because it was referenced elsewhere without resolution. The original remote is recognized as a security+2.0 at 390Mhz. Would a normal read or a raw read be preferred for this?

Send both RAW and signal you got from regular read

**Comment by victor-s-yip** [comment]
Attached is a .zip with the Raw and read (315 Mhz) for the working remote as well as copies of the "Add manually" that were able to register successfully, but not operate the door, 310, 315, and 390 Mhz.

[Remote_files.zip](https://github.com/DarkFlippers/unleashed-firmware/files/11583109/Remote_files.zip)

**Comment by xMasterX** [comment]
> Attached is a .zip with the Raw and read (315 Mhz) for the working remote as well as copies of the "Add manually" that were able to register successfully, but not operate the door, 310, 315, and 390 Mhz.
> 
> [Remote_files.zip](https://github.com/DarkFlippers/unleashed-firmware/files/11583109/Remote_files.zip)

Good, thanks, I found an issue and fixed that, different receivers uses different button codes, I added some of them, but yours was not in the list, now its supported
Install release 050 when it will be published (soon), and try this: Add manually - SecPlus 2.0, Then hold Right arrow button in emulate screen to emulate button with `0x78` code like in your original remote, bind that remote to receiver using only that button, all should work
