### ISSUE TITLE
Car key fob crack

### ISSUE THREAD

**Issue by utenus** [DarkFlippers/unleashed-firmware#480]
### Description of the feature you're suggesting.

I guess this is one of the more difficult tasks. We will need a lot of reverse engineering, but it's worth adding functionality to Flipper Zero from Fantom Grabber for cracking car key security.

https://agentgrabber.com/en/product-category/code-grabbers/pandora-code-grabbers/
https://agentgrabber.com/en/product-category/code-grabbers/crypto-grabber/

https://www.youtube.com/watch?v=wRrM7-bxed8
https://www.youtube.com/watch?v=sNqBJIvwzV4

**Comment by assasinfil** [comment]
The ability to hack car keys is unlikely to be added to this firmware because it is illegal. Still, playing around with the light and stealing a car is a big difference.
