### ISSUE TITLE
german QWERTZ keyboard layout for badusb

### ISSUE THREAD

**Issue by tom-jm69** [DarkFlippers/unleashed-firmware#485]
### Description of the feature you're suggesting.

Add a keyboard option for using qwertz keyboard layout in bad usb.

### Anything else?

When using badusb, most of the scripts won't work on a computer with a qwertz layout.

**Comment by xMasterX** [comment]
open script and click left button "config"

then select layout, german layouts are present! you just not even checked

**Comment by tom-jm69** [comment]
oh sorry, i didn't know that this option existed, my bad
