### ISSUE TITLE
What do I do If I get this error?

### ISSUE THREAD

**Issue by Star300MS** [DarkFlippers/unleashed-firmware#486]
Start Update @Aichonon ERROR: Manifest folder not found
[DEV] Full Update @Aichonon ERROR: Manifest folder not found

Idk what it means but it wont let me download unleashed
I downloaded unleashed yesterday and now I just plugged it into my computer and updated it from qflipper. what do I do?

**Comment by xMasterX** [comment]
Use web updater and follow instructions, first line says - install latest official firmware when you got your flipper out of the box, looks like its your case
