### ISSUE TITLE
Issues Setting "Primary Favorite App" in unlshd-050

### ISSUE THREAD

**Issue by hotdjdave** [DarkFlippers/unleashed-firmware#488]
### Describe the bug.

Upgraded to **unlshd-050**, now setting Primary Favorite App has issues.  I used to be able to select "Applications" as an option and it would let me go down further in the tree to select and actual app.  However, now it only allows me to choose the first level of the tree:  Application, Sub-GHz, Sub-GHz Remote, 125 kHz RFID, etc., without letting me go deeper into the selection.  

### Reproduction

Select:
1).  Settings
2).  Desktop
3).  Primary Favorite App
4).  Applications (or any other in menu)

**Comment by hotdjdave** [comment]
https://github.com/DarkFlippers/unleashed-firmware/assets/130207130/a4e594c1-9ed9-4b2c-b903-7267c35e00aa

**Comment by xMasterX** [comment]
Have you tried scrolling to the bottom? Now it says [External app]
