### ISSUE TITLE
Remote control screen share blank

### ISSUE THREAD

**Issue by Tornadoalley** [DarkFlippers/unleashed-firmware#494]
Issue: In the Flipper App, I am able to remotely control the flippers buttons but the screen share is blank. ![image](https://github.com/DarkFlippers/unleashed-firmware/assets/73433060/d2b8a269-3aea-40aa-99c0-632a0505c038)

Reproduce: Open flipper app > hub > remote control

**Comment by xMasterX** [comment]
this issue cannot be reproduced, this can happen only if you don't wait until its synced, and open that while its syncing, just wait and reopen remote control in hub

**Comment by Tornadoalley** [comment]
Thanks, syncing is stuck at 0%. What should I do?

**Comment by Tornadoalley** [comment]
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/73433060/9fec1653-c803-48d5-a06a-2fba6241924b)

**Comment by xMasterX** [comment]
Check your sd card root folder using flipper's file browser

Delete macOS or windows leftovers that may be sitting in root of sd card, like SystemVolumeData or .fsevents or things like that

**Comment by Tornadoalley** [comment]
Thanks, I will try that

**Comment by Tornadoalley** [comment]
Here is what I found:![image](https://github.com/DarkFlippers/unleashed-firmware/assets/73433060/9cd27834-f8a5-4b1f-838c-4b667949733f)

**Comment by xMasterX** [comment]
> Here is what I found:![image](https://user-images.githubusercontent.com/73433060/242913692-9cd27834-f8a5-4b1f-838c-4b667949733f.png)

Please read my message, first of all delete that Applications folder, and fix nfc, subghz folders names
And remove windows hidden folders on flipper itself, windows won't allow you do to it, use flipper's filebrowser

**Comment by xMasterX** [comment]
I'd recommend - copy your keys and backup other files you need, then format microsd and do clean install of latest release

**Comment by Tornadoalley** [comment]
Thanks, can I use the online file browser?

**Comment by xMasterX** [comment]
> Thanks, can I use the online file browser?

Use file browser on flipper itself, you don't know how to open it?
Web may hide those files too

Down arrow on main screen, then click left
Hold center button on folder and select remove

**Comment by Tornadoalley** [comment]
I like to use FlipperLab online since I find it easier but I also use the built in file browser. Where are the keys stored?

**Comment by Tornadoalley** [comment]
There is a file named FOUND.000 
Could that be causing the issue?
