### ISSUE TITLE
Battery level shared with Bluetooth

### ISSUE THREAD

**Issue by ErSeraph** [DarkFlippers/unleashed-firmware#495]
### Describe the enhancement you're suggesting.

Using an Android 13 with a Google Pixel 7, you can view the battery level of all your bluetooth devices on the statusbar, AOD, Home screen, Lock screen and notified if the battery is dying, great function and I like using it. This function actually work if you use plugins like Bluetooth Remote, but the standard connection show me the Flipper as generic device whitout the battery level shared (or it's my problem only?). You can view the battery level using te official Flipper app, but it can be useful if the Android OS (and iOS) can detect the Flipper with the battery system.

### Anything else?

Actually I don't know if this already work, I have a smartwatch and for some reason I cannot see the battery level anymore, anyway Im available for some testing purposes.

There is an image showing that widget (Not my smartphone): https://9to5google.com/wp-content/uploads/sites/4/2022/03/Screenshot_20220307-140324.png?w=473

**Comment by Tornadoalley** [comment]
Here is what it looks like on iOS![image](https://github.com/DarkFlippers/unleashed-firmware/assets/73433060/69043318-aec6-4e34-8cf2-e44919a0c33b)

**Comment by MorevPro** [comment]
im not sure, that is a good feature, becouse it will be needed more connections via bt and this will significantly reduce the battery charge.

**Comment by MichaelK-F** [comment]
This has already been done with the badbt on the flipper. If you have a phone or laptop paired to control [flipper name], then it will show the battery percentage.

**Comment by ErSeraph** [comment]
You're right, I actually forgot I never closed this issue
