### ISSUE TITLE
Empty pcaps from marauder 

### ISSUE THREAD

**Issue by ganshtel** [DarkFlippers/unleashed-firmware#501]
### Describe the bug.

Sniffing via Marauder and saving files to SD-card leads to empty pcap-files. 
At least versions 051e and 052e.

### Reproduction

1. Turn on Flipper Zero Wi-Fi Module v1
2. Run Marauder "Applications -> GPIO -> Marauder"
3. Sniff in any way(Active/Passive/etc)
4. Download Directory /ext/apps_data/marauder SUCCESS
5. ~/Downloads/marauder$ du -h  pcaps/
  0B	pcaps/
   ~/Downloads/marauder$ ls pcaps/ | wc -l
      65

**Comment by ganshtel** [comment]
BTW logs are fine

**Comment by xMasterX** [comment]
Looks like you didn't follow instructions
