### ISSUE TITLE
BadUSB file recognition error

### ISSUE THREAD

**Issue by ggrzr** [DarkFlippers/unleashed-firmware#505]
While trying to use BadUSB feature on flipper i encoutered strange problem in file system. Attaching screenshots below. No additional scripts were installed.
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/95701178/85cfffa6-9e1c-46e2-b995-fed1925a9525)
And in quick menu. Same thing
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/95701178/72db4efd-015c-4e33-a958-d36ed8c2bc7a)

However in desktop app it shows folder assets and nothing more.
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/95701178/5dede523-747c-4878-8923-71fc2d414b99)

Didn't encouter any problems while using this SD card, benchmark passed. 
Used version of firmware: unleashed 052 and 052e

### Reproduction

1. Reboot flipper if needed
2. Open BadUSB app

### Target

BadUSB

### Logs

```Text
DESKTOP APP
262443 [RPC] (13) Storage List @/ext/badusb START
262518 [RPC] (13) Storage List @/ext/badusb SUCCESS

INTERNAL LOGS (from mobile app)
[XX:10:33][error]: verify region: StorageError: File/Directory does not exist
```

**Comment by xMasterX** [comment]
looks like your sd card is bad, nothing in latest release can cause such behaviour except broken filesystem on your microsd
