### ISSUE TITLE
Sub GHz App- reproducible freeze with certain sequence of actions (firmware 52e)

### ISSUE THREAD

**Issue by eriknyquist** [DarkFlippers/unleashed-firmware#506]
### Describe the bug.

Sub GHz app freezes, requiring device reset with left + back buttons, when scrolling through modulation options with hopping enabled, AND after HND_2 modulation was enabled for a short time

### Reproduction

1. Open Sub GHz "Read" app.
2. Press left to open config menu
3. Set "Hopping" to ON
4. Set "Modulation" to HND_2 (all the way to the right)
5. Press back button, let the frequency hopping w/ HND_2 run for a second or two
6. Press left to go back into config menu
7. Scroll left through the modulation options, this causes the freeze,  for me it always freezes on FM476

### Target

Flipper zero, firmware 52e

### Anything else?

This is not new, I also observed this in 49e

**Comment by xMasterX** [comment]
Fix will be published soon
