### ISSUE TITLE
Crash while idle. 

### ISSUE THREAD

**Issue by Moonbase1** [DarkFlippers/unleashed-firmware#511]
### Describe the bug.

Flipper crashed and was rebooted

ST(R) Copro(R) HardFault

happens multiple times a day while the flipper is idle. Flipper is not running any other additional software packages. 

### Reproduction

Running current Unleashed firmware release

Let sit idle.

**Comment by xMasterX** [comment]
Please do not make duplicate issues, read this thread #449

And follow latest message advice, also will be good if you test that on next release 053, since some fixes was made to reduce that issue to the minimum
