### ISSUE TITLE
AVR ISP Programmer won't dump an AVR since unlshd-051

### ISSUE THREAD

**Issue by p0ns** [DarkFlippers/unleashed-firmware#525]
### Describe the bug.

I was attempting to dump an ATTiny85 using AVR ISP Programmer on unlshd-054 and it kept crashing with `furi_check failed`. 

I tested a few versions back, and I got the following results 
- unlshd-049, dump works
- unlshd-050, dump works
- unlshd-051, `furi_check failed`
- unlshd-052, `furi_check failed`
- unlshd-054, `furi_check failed`

The bug seems to affect Dump AVR and Flash AVR, but ISP Programmer functionality still works.

This leads me to believe that something was introduced on 051 that broke AVR ISP Programmer. If there's anything I can do or provide to help fix this, I'd be happy to help. I've not tested on vanilla firmware.

### Reproduction

1. Connect an AVR chip to the flipper zero, tested with ATTiny85 and ATMega328PB
3. Open AVR Flasher
4. Go into Dump AVR
5. It should detect the chip connected
6. Press Next >
7. Press center to save
8. Press center to start the dump
9. Flipper crashes

**Comment by xMasterX** [comment]
thanks, fixed now, will be published soon
