### ISSUE TITLE
User Dict MF Keys multiple deleted

### ISSUE THREAD

**Issue by cozzm0** [DarkFlippers/unleashed-firmware#532]
### Describe the bug.

When deleting one key, two keys are deleted at a time instead of just the one key. 

### Reproduction

Open Mifare Classic Keys
View list (user dict)
Select first key on list
Press right to delete and first key and second key will be deleted. 

### Anything else?

Have had 3 keys deleted at once (list went from 5 to 2 keys when playing around, but I don’t recall how o made that happen). 
Version 052

**Comment by UrSuLa360** [comment]
Yes, reproducible in 055 too.

Deleting a key also remove some extra "\n" or "\r\n" 

From: (5 keys)

key1
key2
key3
key4
key5

To: (2 valid keys + 1 bugged key)

key1
key2key4
key5

Nice catch @cozzm0

**Comment by xMasterX** [comment]
Fixed in dev, thanks
