### ISSUE TITLE
[unlshd-056] sub-ghz menu causes device crash after update

### ISSUE THREAD

**Issue by S1lkys** [DarkFlippers/unleashed-firmware#538]
### Describe the bug.

See https://github.com/flipperdevices/flipperzero-firmware/issues/2854 
 the fix is also included. I recognized this Bug in unlshd-056.

### Reproduction

See https://github.com/flipperdevices/flipperzero-firmware/issues/2854

**Comment by S1lkys** [comment]
I fixed it by deleting subghz/assets then uploading https://github.com/DarkFlippers/unleashed-firmware/tree/dev/assets/resources/subghz/assets again

**Comment by xMasterX** [comment]
assets wasn't changed for a long time, looks like issue was one time non  with your microsd card also
I can't replicate this on two flippers, subghz works correctly after update

**Comment by cokyrain** [comment]
Are you connected flipper to mobilephone using bluetooth?

**Comment by z3razerviper** [comment]
Overall mine has been crashing quite often with just about everything (including nfc) from v56 on. Its  been less than 30 min on v58 has already crashed once just while sleeping....
