### ISSUE TITLE
U2F Security Key not supported in Windows 11

### ISSUE THREAD

**Issue by SystemOfTheCSGO** [DarkFlippers/unleashed-firmware#540]
### Describe the bug.

The current module of security key U2F is not supported by windows.

### Reproduction

Use the firmware as usual, get a clean install of windows 11, try to link the security key from flipper to windows, you will get a error: this device is not certified.

### Anything else?

This can be bypassed emulating headers of a certified key.

**Comment by xMasterX** [comment]
This is not "bug" with our firmware, you will see same results on official firmware
Create issue in their repo about this, but I can already tell the answer - it will not be bypassed
Microsoft asks to pay for certification, also github is owned by them, so this is not a good place to even discuss that
