### ISSUE TITLE
Authenticator app error + flipper crash

### ISSUE THREAD

**Issue by SilentMonster0** [DarkFlippers/unleashed-firmware#547]
### Describe the bug.

from what i know, on version 056e, when you open the authenticator app you get an error that says "an error has occured during loading config file" and when you go back, the flipper crashes with a "null pointer dereference"

![Screenshot-20230714-145619](https://github.com/DarkFlippers/unleashed-firmware/assets/76798254/3d3e9309-7f90-4a5b-b758-ecd939e0933d)
![Screenshot-20230714-145649](https://github.com/DarkFlippers/unleashed-firmware/assets/76798254/a0a5ea6b-708d-4a5f-a127-18b84ac9ff01)

### Reproduction

1. go to applications
2. go to tools
3. open the authenticator app
4. you get an error and flipper crashes when you go back

**Comment by UrSuLa360** [comment]
it is working for me, i had no previous tokens. I can enter the app and create new tokens. Later i can exit/enter the app multiple times and check the auth code  without problem.

Did you have previous tokens saved before upgrading to the lastest version?
What was the previous version you was using before upgrading to 056e?

**Comment by SilentMonster0** [comment]
i dont think i have any tokens. 
the previous version I was using before 056e was the one before it (055e)

**Comment by SilentMonster0** [comment]
**UPDATE: i fixed the bug lol all i had to do was delete the authenticator folder and also deleted the apps folder just to be safe then reinstalled the firmware, I can use it now**
