### ISSUE TITLE
[NRF24] Sniffer writes in another path than [NRF24] Mouse Jacker starts.

### ISSUE THREAD

**Issue by LupusE** [DarkFlippers/unleashed-firmware#551]
### Describe the bug.

Since version unlshd-057 the application `[NRF24] Sniffer` is writing to a different folder than `[NRF24] Mouse Jacker` is searching

I can't find where `[NRF24] Sniffer` set the path `apps_data/nrf24_sniffer` for the file `addresses.txt`.
[nrfsniff.c](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/external/nrfsniff/nrfsniff.c) Line 17 seems to be only half the truth:
```
#define NRFSNIFF_APP_PATH_FOLDER STORAGE_APP_DATA_PATH_PREFIX
```

The application `[NRF24] Mouse Jacker` is searching in `apps_data/nrf24sniff/addresses.txt`
[mousejacker.c](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/external/mousejacker/mousejacker.c) Line 18:
```
#define NRFSNIFF_APP_PATH_FOLDER_ADDRESSES EXT_PATH("apps_data/nrf24sniff/addresses.txt")
```

### Reproduction

1. From Flipper Zero start screen, click middle Button
2. Select `Applications`
3. Go into `GPIO`
4. Start `[NRF24] Sniffer`
5. Press middle Button to set 'Sniffing: Yes'
[wait until the module found something]
6. even nothing is found, there is a new folder `apps_data\nrf24_sniffer`
7. If there is a address.txt, the app `[NRF24] Sniffer` will not start, because it searches for `apps_data\nrf24sniff`

Rename the folder does the trick (Thanks for implementing the new actions in FZ Browser!)

### Target

unlshd-057 

### Anything else?

EDIT: Found it in [storage_processing.c](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/services/storage/storage_processing.c), line 469. The path is dynamic created from [APPID](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/external/nrfsniff/application.fam).

So the path in `mousejacker.c` needs to be fixed.

**Comment by xMasterX** [comment]
Thanks! Fixed in dev branch
