### ISSUE TITLE
Write to populated MIFARE CLASSIC 1K card

### ISSUE THREAD

**Issue by rapbando** [DarkFlippers/unleashed-firmware#560]
### Describe the enhancement you're suggesting.

Right now is only possible to write a properly saved nfc card to a initlal card (bank or virgin), while other [tools](https://play.google.com/store/apps/details?id=de.syss.MifareClassicTool)  are able to overwrite the same card and blank ones.

**Comment by wosk** [comment]
Use "Nfc magic" application to write gen1a/b and gen4 mifare tags

**Comment by rapbando** [comment]
Under NFC magic there is only two option:

- Check magic tag
- Authenticate Gen4

No option to write, let alone a MIFARE Classic 1K...

**Comment by liszkai** [comment]
The next menu depend on your magic tag version. Use "Check magic tag", then you can write it.
![magictag1](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/c1bf7cfb-d434-4343-80d4-f0f8ebca0c66)
![magictag2](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/9093cf31-1bab-41d8-9466-9a232ea21b90)
![magictag3](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/8443f477-9d1a-4ee2-a5bc-04e81b575800)

**Comment by rapbando** [comment]
@liszkai 

That only works for magic tags not for MIFARE Classic 1K...

@xMasterX  Please reopen the issue because is not solved.
