### ISSUE TITLE
[NFC] Fail to fully read a mifare classic 1k card with valid keys in user dictionary

### ISSUE THREAD

**Issue by UrSuLa360** [DarkFlippers/unleashed-firmware#567]
### Describe the bug.

I read Mifare classic card 1k with 5 unknown B keys. 
![Screenshot-20230804-125853](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/0ff77b82-0fe8-42a7-af07-a1654d8bfc19)

Now i try to recover keys with Mifare Nested by @AloneLiberty 
![Screenshot-20230804-130044](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/bf79815c-bf72-43a2-9b7c-e3ebbfe0215e)

`python -m FlipperNested
[?] Checking 0EFB2C68.nonces
[!] No nonces found
[!] Failed to parse 0EFB2C68.nonces
[?] Checking DCC57129.nonces
Recovering key type B, sector 11
Found 1 key(s): ['8ae675fb1067']
Recovering key type B, sector 12
Found 1 key(s): ['aa3a9cf1c6f7']
Recovering key type B, sector 13
Found 1 key(s): ['2595b1d36a23']
Recovering key type B, sector 14
Found 1 key(s): ['91f69383da4d']
Recovering key type B, sector 15
Found 1 key(s): ['0abf7fedf635']
[+] Found potential 5 keys, use "Check found keys" in app`

![Screenshot-20230804-130244](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/1bfe1351-a9ce-483b-b57e-8196e7cbd1a4)

The mf_classic_dict_user.nfc after "check found keys" process results in: (the key  669957a21cb8 was already in dict)

669957a21cb8
8AE675FB1067
AA3A9CF1C6F7
2595B1D36A23
91F69383DA4D
0ABF7FEDF635

Then with keys in dict i read the card again.

![after_adding_keys](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/f0b6c4b6-2c61-4221-bc54-e7176562d74f)

Same result even with keys in dict.

The keys are valid, i can unlock the card with moc in the computer. 

Anything let me know. Thank you

### Target

NFC

### Anything else?

unlshd-059

**Comment by AloneLiberty** [comment]
As you pinged me, I see its B keys, might be fixed with https://github.com/flipperdevices/flipperzero-firmware/pull/2912. Just to be sure, can you check on latest dev OFW version?

**Comment by UrSuLa360** [comment]
![Screenshot-20230804-142834](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/d71787cc-287a-478d-9550-e95cc14004f1)

Latest dev OFW Worked.

Thanks! You're awesome!

(i think your changes will be released here soon, then i will recheck again and close the issue)

**Comment by xMasterX** [comment]
> ![Screenshot-20230804-142834](https://user-images.githubusercontent.com/125646802/258419774-d71787cc-287a-478d-9550-e95cc14004f1.png)
> 
> Latest dev OFW Worked.
> 
> Thanks! You're awesome!
> 
> (i think your changes will be released here soon, then i will recheck again and close the issue)

Can you check with latest dev build?
[Link to web updater](https://lab.flipper.net/?url=https://unleashedflip.com/fw/dev/flipper-z-f7-update-755.tgz&channel=dev-cfw&version=755)

**Comment by UrSuLa360** [comment]
![Screenshot-20230805-164326](https://github.com/DarkFlippers/unleashed-firmware/assets/125646802/8c5a4a3a-5a16-4273-a4c9-94883305f88c)

Latest unleashed dev version Worked! 

I got the version from this link
[https://lab.flipper.net/?url=https://unleashedflip.com/fw_extra_apps/flipper-z-f7-update-757e.tgz&channel=dev-cfw&version=757e](url)

PD: your link didn't work, "Failed to fetch"

**Comment by xMasterX** [comment]
> ![Screenshot-20230805-164326](https://user-images.githubusercontent.com/125646802/258591407-8c5a4a3a-5a16-4273-a4c9-94883305f88c.png)
> 
> Latest unleashed dev version Worked!
> 
> I got the version from this link [https://lab.flipper.net/?url=https://unleashedflip.com/fw_extra_apps/flipper-z-f7-update-757e.tgz&channel=dev-cfw&version=757e](url)
> 
> PD: your link didn't work, "Failed to fetch"

yea build was a bit outdated
thanks!
all will be in 060 release, for now i'm closing this issue
