### ISSUE TITLE
NFC manually added NFC-A 4-bytes UID ATQA bytes inverted

### ISSUE THREAD

**Issue by t0m4-null** [DarkFlippers/unleashed-firmware#572]
### Describe the bug.

On version 60e, if I manually add a NFC-A 4-bytes UID, the ATQA bytes saved are inverted.

### Reproduction

1. Go to NFC > Add Manually > NFC-A 4-bytes UID
2. Set 08 as SAK
3. Set 00 04 as ATQA
4. Set 00 11 22 33 as UID
5. Set "Test" as name
6. Go to NFC > Saved
7. Select  Test
8. Select Info

Here, you can read:

```
Unknown ISO tag
ISO 14443-3 (NFC-A)
UID: 00 11 22 33
ATQA: 04 00  SAK: 08
```

(and the inverted ATQA bytes issue is confirmed when emulating this UID)

**Comment by Leptopt1los** [comment]
Solved here: https://github.com/DarkFlippers/unleashed-firmware/commit/4e068ba59316201bfaeea29eb708def7905b113f
Fix will be included to next release
