### ISSUE TITLE
Sub-GHz app is not present in Apps/Sub-GHz menu

### ISSUE THREAD

**Issue by hradyho** [DarkFlippers/unleashed-firmware#575]
### Describe the bug.

Not sure if this is wanted behaviour, but agains of any other main menu app (NFC, RFID, iButton, GPIO, BadUSB, etc.) **Sub-GHz** app is not present in **Apps > Sub-GHz** menu (and also not on SD card - checked resource.tar file of fw060, and also there is .fap missing in apps folder). 

I found difference in app manifest: https://github.com/DarkFlippers/unleashed-firmware/blob/aeadaef7c9702202cc59b9141ba583e4d731fa92/applications/main/subghz/application.fam#L4 But not sure if just change this to `FlipperAppType.MENUEXTERNAL` will solve issue.

### Reproduction

1. Open main menu
2. Click Apps
3. Click Sub-GHz
4. Missing Sub-GHz app here

**Comment by gid9798** [comment]
SubGhz App returned to flash, this leaves more free RAM for receiving signals.

**Comment by xMasterX** [comment]
This is not a bug, read gid9798's message, our subghz implementation can't work as external plugin as is with all protocols
max signal count will be at 20-25 instead of 55
it was moved back to internal 

If you have idea how to make more space in RAM share it with us
