### ISSUE TITLE
Mobile App file downloads/Marauder pcaps

### ISSUE THREAD

**Issue by darkiron71** [DarkFlippers/unleashed-firmware#587]
### Describe the enhancement you're suggesting.

I am looking to see if it is possible to modify directory access to allow downloads via the mobile app. More specifically, I want to download pcap files from the /ext/apps_data/marauder/pcaps . When accessing this directory from the mobile app all pcap files are grayed out and unavailable for download. I am able to download the log files just fine to the mobile app so I am unsure why all files in the pcap directory are unable to be accessed via the app. I suspect it is some type of permissions issue on the folder itself, but I am unable (or don't know how) to change the folder permissions to allow downloads. Can this feature be included in a future version? Or are there instructions on how to modify directory access to allow for pcap file downloads to the app?

Any help on this is much appreciated!

**Comment by xMasterX** [comment]
How mobile app file manager issues could be related to firmware?
nothing is blocked on firmware side, also file system has no such option as "permissions"
files are restricted on mobile app side, create issue in the correct repo
