### ISSUE TITLE
Adding custom protocols

### ISSUE THREAD

**Issue by nickyg543** [DarkFlippers/unleashed-firmware#593]
### Describe the enhancement you're suggesting.

I'd like to define a SubGHz protocol for the flipper, but I'm not sure where to get the hex code for the CC1101 (like shown below)
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/103463122/24d84abd-6366-4e75-b2c9-a1b7b6c18c41)
Is there a guide anywhere describing how to do this? Use TI's SMARTRF studio?

**Comment by nickyg543** [comment]
Update: adding to setting_user does not update the frequency list in the GUI, nor does it add new protocols
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/103463122/dc0a1598-699c-4480-9a1a-e2fa0a69d760)
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/103463122/24889c31-9156-4eac-93c1-7cd7fabac7eb)
How should I go about adding protocols and frequencies?

**Comment by wosk** [comment]
1. RTFM cc1101 datasheet for registry sequence coding (hex code) to add new protocol.
2. You have to uncomment Frequency line in setting_user file to enable it

**Comment by xMasterX** [comment]
Please read @wosk response, and follow his recommendations
