### ISSUE TITLE
Integrate Apple Bluetooth Low Energy (BLE) and ADV Packets Prank

### ISSUE THREAD

**Issue by zelorun** [DarkFlippers/unleashed-firmware#598]
### Description of the feature you're suggesting.

Apple devices can be spammed using bluetooth, see:

https://techryptic.github.io/2023/09/01/Annoying-Apple-Fans/

**Comment by syxanash** [comment]
This would be a nice to have 😄

**Comment by m1ga** [comment]
it's already included in the dev branch + extra apps.

and the same issue was posted right below yours https://github.com/DarkFlippers/unleashed-firmware/issues/597 @zelorun

**Comment by zelorun** [comment]
@m1ga which command to use if i want to build locally with extra apps?

**Comment by m1ga** [comment]
Check the `#unleashed-development` channel in discord. It has links to the webinstaller for every commit. Otherwise it is a normal build (commands are in the readme) and use the zip from https://github.com/xMasterX/all-the-plugins. Again: readme

**Comment by xMasterX** [comment]
App is integrated in dev builds and will be in next release
