### ISSUE TITLE
Flipper crashes and reboots

### ISSUE THREAD

**Issue by Scrut1ny** [DarkFlippers/unleashed-firmware#603]
### Describe the bug.

In v63 if you turn off Bluetooth, then click the back button the flipper freezes and then restarts. Once it restarts the error code is "furi_check failed"

### Reproduction

1. Turn off Bluetooth in settings
2. Click the back button

### Target

Bluetooth

### Logs

```Text
"furi_check failed"
```

### Anything else?

I tried this multiple times and had the same result, but after doing it about 6 times it just stopped failing and working perfectly again. I tried hooking it up to my pc to obtain the logs but I couldn't recreate the error anymore.

**Comment by xMasterX** [comment]
Can't replicate this issue, reopen when you find way to replicate it in more stable way
