### ISSUE TITLE
Enhance BLE Attacks: Prompt for Bluetooth Activation When Disabled

### ISSUE THREAD

**Issue by Scrut1ny** [DarkFlippers/unleashed-firmware#604]
### Describe the enhancement you're suggesting.

If you disable Bluetooth in the settings and subsequently attempt to run BLE Attacks, they still execute despite Bluetooth being turned off. It would be more helpful if a prompt appeared, suggesting that you enable Bluetooth since it's currently switched off. Users might forget that they disabled Bluetooth and proceed to run the BLE Attack app, mistakenly thinking it's functioning when it's not.

**Comment by nocerainfosec** [comment]
Apple BLE Spam seems not to be working, is it an issue with my flipper?

**Comment by Scrut1ny** [comment]
> Apple BLE Spam seems not to be working, is it an issue with my flipper?

I don't think so, make sure Bluetooth is enabled and your on v63 of the firmware that just dropped. Try also restarting your flipper or flashing it again.

**Comment by xMasterX** [comment]
Bluetooth is not required to be enabled, app enables and disables it by itself
