### ISSUE TITLE
USB Keyboard: Add special keys for BIOS control

### ISSUE THREAD

**Issue by xhd4** [DarkFlippers/unleashed-firmware#606]
### Description of the feature you're suggesting.

Is it possible to add a standard set of keys for BIOS control? Apps -> USB -> USB Keyboard & Mouse
F2,F8,F10,F12,
ESC,DEL,
LEFT,RIGHT,UP,DOWN,
ENTER,SPACE

**Comment by xMasterX** [comment]
All those keys are present, try clicking up arrow until you see extra key rows, and same for bottom key rows, all F keys are present in upper row and other keys too, in bottom rows
