### ISSUE TITLE
bug screen update flipper-z-f7-update-unlshd-064r.tgz

### ISSUE THREAD

**Issue by Alfa16bravo** [DarkFlippers/unleashed-firmware#630]
### Describe the bug.

hello, I installed the new update flipper-z-f7-update-unlshd-064r.tgz
and since then no backlight

### Reproduction

no backlight

**Comment by UrSuLa360** [comment]
Have you checked the value in
_Settings -> LCD and Notifications -> LCD Backlight_
?

**Comment by Alfa16bravo** [comment]
yes a checked, LCD brightness at 100%

**Comment by xMasterX** [comment]
Lets read what build with `r` means, and think about rgb leds that can't grow up by themselfs, you have to modify hardware of your flippper

<img width="731" alt="Screenshot 2023-10-13 at 17 44 12" src="https://github.com/DarkFlippers/unleashed-firmware/assets/10697207/aa4df8a3-dc60-4b90-979f-daae8924c4d3">
