### ISSUE TITLE
Flipper crashed and screen went blank on FW 064e

### ISSUE THREAD

**Issue by BlackMercy** [DarkFlippers/unleashed-firmware#631]
### Describe the bug.

Couple weeks ago I flashed my Flipper from stock FW to unlshd-063e (first time using custom firmware) using qFlipper and it worked fine. Four days ago I saw that FW 064e was released so I flashed it using qFlipper and it was fine until yesterday as I was opening NFC app -> Detect Reader this is when the device crashed and the screen went blank. I'm not entirely sure if it's crashed before or after I open 'Detect Reader' but it was just about the same time.

I tried charging but it didn't do anything. No red LED. (battery level was at around 70%). Today I tried pressing Left + Back and it woke up with the message:

`Flipper crashed and was rebooted; out of memory`
[(Screen image)](https://imgur.com/a/7BxRSER)

I thought I would report it here. I don't know if there's more logs that I can provide. Please let me know if I can get system log for the development team.

Or if this is a known issue and there's anything I can do to prevent this from happening again, please let me know.

Thanks.

### Reproduction

This is entirely random so I don't have the reproduction steps.

When it happened I was entering NFC app and enter 'Detect Reader' and it crashed.

**Comment by xMasterX** [comment]
Can't reproduce, also NFC system was replaced with new one, which should not have that issues, check dev builds and dev branch
