### ISSUE TITLE
API Mismatch Warnings

### ISSUE THREAD

**Issue by orangetreefrog4** [DarkFlippers/unleashed-firmware#632]
I know about the API mismatch warnings and why they happen, but since unleashed is based on stock, is it possible to safely remove the warnings for apps on the stock plugin/app API?
The only reason I bring this up as an issue is because all of my stock apps are said to be unsafe as of using the stock API and in some cases I remember having to reinstall some stock apps.
It's not that big of an issue but maybe it's still one to keep in mind.

This is the warning I'm talking about:
![image](https://github.com/DarkFlippers/unleashed-firmware/assets/123574555/cbd7ea49-9b3c-43ce-a886-d77eb2212146)

Thanks. 🙂

**Comment by xMasterX** [comment]
API mismatch means apps was compiled with different API

in your case you using outdated apps, use `e` build with all apps preinstalled if you can't keep them updated
firmware build `e` will do it for you, automatically updating them in each release
