### ISSUE TITLE
Learning new remote (infrared) - fw 065e

### ISSUE THREAD

**Issue by m0ng3sh3ll** [DarkFlippers/unleashed-firmware#635]
### Describe the bug.

The feature learning new remote, in the submenu infrared, is not working. 
I am used a new firmware (unlshd-065e)

### Reproduction

1. Menu;
2. Infrared;
3. Learning new remote;

**Comment by xMasterX** [comment]
Issue cannot be replicated, all works fine on 2 test flippers with NECext remote and SIRC remote
