### ISSUE TITLE
LCD brightness

### ISSUE THREAD

**Issue by Shocker-8** [DarkFlippers/unleashed-firmware#637]
### Describe the bug.

Lost LCD brightness control with this new firmware update. The brightness is as if it was at the minimum, but with 100% on the selection. Changing it, does nothing.

### Reproduction

Its on going...

**Comment by wosk** [comment]
Don't write RGB-mode firmware without hardware modification.
You can always revert to stock fw

**Comment by 0xCwrw** [comment]
Having the same issue with unlshd-065r. Any updates on workarounds?

** Edit, again I was the problem and can't read... fixed now :)

**Comment by xMasterX** [comment]
Do not install 'r' build on non modded flippers
