### ISSUE TITLE
Decode Sub GHz with raw files

### ISSUE THREAD

**Issue by 4suino** [DarkFlippers/unleashed-firmware#641]
### Describe the bug.

When attempting to decode AM signals Sub GHz, in certain unclear cases, the operation does not complete successfully. Even though a screen indicating "Decoding Successful" is displayed, Flipper remains on this screen without actually producing the decoded output.

### Reproduction

Decode a raw signal.

**Comment by xMasterX** [comment]
I will replace text, it means finished - not successful
