### ISSUE TITLE
Enable TX restrictions option

### ISSUE THREAD

**Issue by thebashforkbomber** [DarkFlippers/unleashed-firmware#646]
### Description of the feature you're suggesting.

Since in most countries, transmitting on certain frequencies is illegal. Since this FW removes this limitation, that means being illegal. This what effectively scares me. Accidentally sending a signal on an illegal frequency. although the built-in sub-ghz part is very weak (can't go through atleast 3 walls), still.
What I am saying is:
**Add the restriction option for people those are scared to use Sub-GHZ on this fw.**<sup>or atleast add a warning that you are going to break the law</sup>

**Comment by grantgarbe** [comment]
I highly agree.

**Comment by BrianD436** [comment]
I actually use this feature for my garages. I would rather it not be removed.  I can always continue using older versions if I have to.
