### ISSUE TITLE
Screen light turned off

### ISSUE THREAD

**Issue by akai98** [DarkFlippers/unleashed-firmware#651]
### Description of the feature you're suggesting.

After update flipper-z-f7-update-unlshd-065r.tgz,  Screen light to my flipper turned off. How to turn on? Thank

**Comment by liszkai** [comment]
Hi,

The "r" version is for RGB backlite hw mod.
Use "e" version for extra apps, or "c" for only basic apps.

**Comment by xMasterX** [comment]
Next time try to scroll page a bit up and read detailed description about builds that i placed in every release
