### ISSUE TITLE
Add BLE Spam file system

### ISSUE THREAD

**Issue by MakeTotalSense12** [DarkFlippers/unleashed-firmware#656]
### Description of the feature you're suggesting.

For now we can't edit the .fap of the app to create our own BLE Spam display. We can do it in the Xtreme firmware but it's not something I would do everyday.

Can't we just create a folder in the apps_data where we can simply edit a file to create or remove BLE Spam displays?

**Comment by xMasterX** [comment]
This is not how it works, custom ID option is present in the app, hold Ok(Start) to access menu
ble "displays" is not a picture, nothing is loaded from plugin or microsd, app just sends id code that is present in phone os, custom codes are only working on android with popups debug mode enabled, and intended to device manufacturers to test their new products

**Comment by MakeTotalSense** [comment]
@xMasterX pressing Ok(Start) on the BLE Spam > FastPair just turn it on and off very quickly. It doesn't open any menu. I run the last version of unleashed tho
