### ISSUE TITLE
Add Manually Layout bug for Sec+ V1

### ISSUE THREAD

**Issue by Crsarmv7l** [DarkFlippers/unleashed-firmware#658]
### Describe the bug.

When creating a Sec+ v1 remote via Add Manually in Unleashed Release version 65 the layout is off so the counter cannot be read. 

Interestingly the layout of a Sec+ v1 remote I created long ago on version 13 I think, is still fine when opened. It only happens if I create a new Sec+ v1 remote on Unleashed 65.

![Sec+ Bug](https://github.com/DarkFlippers/unleashed-firmware/assets/85343771/90424e7c-37e9-44a5-b7fe-0ffa74f111ce)

### Reproduction

Create Sec+ v1 remote on Unleashed v65 Release

**Comment by Crsarmv7l** [comment]
Some new info I just found. If I rename the file to Sec1 while creating it  (as I did when I noticed the issue) it appears as above. If I save as whatever name flipper wants to give it, it renders correctly in the display. Here are both files with .txt tacked on after .sub.
[Mini_anomalija.sub.txt](https://github.com/DarkFlippers/unleashed-firmware/files/13469180/Mini_anomalija.sub.txt)
[Sec1.sub.txt](https://github.com/DarkFlippers/unleashed-firmware/files/13469181/Sec1.sub.txt)

**Comment by xMasterX** [comment]
Fixed
