### ISSUE TITLE
Pocsag pager crash

### ISSUE THREAD

**Issue by Chiragwelekar** [DarkFlippers/unleashed-firmware#670]
Whenever opening the pocsag pager flipper zero is crashing. Some of the apps are causing flipper zero to crash and restart

**Comment by xMasterX** [comment]
> Whenever opening the pocsag pager flipper zero is crashing. Some of the apps are causing flipper zero to crash and restart

Pocsag pager works fine, you provided no info about your firmware version and no steps to reproduce described issue
What about other apps? Do you have their names at least?
