### ISSUE TITLE
066e NFC write to inital card

### ISSUE THREAD

**Issue by reidandrew91** [DarkFlippers/unleashed-firmware#676]
### Describe the bug.

Updated to 066e yesterday. After doing so, i have 1 NFC  card that has the feature to Write to Inital card. It kept failing. Changed data in card by using it, tried writting again, it failed again.

Revert to 65e and the function worked again. 

### Reproduction

On 66e, try to a NFC-a MiFare Classic card by using Write to Initial card. 

Error is "Writting gone wrong. Not all sectors were written correctly".

Go back to 65e and try again, it will work. 

### Anything else?

Please confirm you are getting the same error.

**Comment by Leptopt1los** [comment]
@reidandrew91 Please check this issue on the latest unleashed release. also check it on another card if you have the opportunity. Most likely, the problem is with your specific card
