### ISSUE TITLE
Documentation Request: android functionality

### ISSUE THREAD

**Issue by EvanCarroll** [DarkFlippers/unleashed-firmware#679]
### Describe the enhancement you're suggesting.

It would be nice to see it documented what android app we're supposed to use. It seems the official Android app doesn't support third party firmwares but I've opened an issue to request clarification there too.  https://github.com/flipperdevices/Flipper-Android-App/issues/754

However, there is a Flipper Unleashed Android app too, https://github.com/DarkFlippers/Unleashed-Flipper-Android-App

That seems to be unsupported, so it seems we're not supposed to use that. But it clarity would be nice.

After pairing my Flipper w/ Flipper Unleashed with my Android cell using the F-Droid provided APK for the app, I get

![signal-2023-12-23-182634_002](https://github.com/DarkFlippers/unleashed-firmware/assets/19922/8ba0446a-d7d5-403b-b96c-fd43abe51818)

**Comment by xMasterX** [comment]
You just need to forget all devices on flipper and forget flipper in the mobile app and pair it again, all works and all is supported
Looks like you missed all steps from our installing instruction
