### ISSUE TITLE
Unable to emulate classic Mifare classic 1k iso 144443-3(nfc-a)

### ISSUE THREAD

**Issue by Pmacdon15** [DarkFlippers/unleashed-firmware#685]
### Describe the bug.

I am able to read card no problem, how ever when I try to ready an emulated card from the flipper on my Arduino RFID scanner, the scanner can read the cards but not the flipper. I also tried an NFC app on my phone which reads the cards same info but dose not read the flipper. I had unleashed 66 which mentions something, I updated to 67, still have the same issue.  

### Reproduction

1. read card
2. emulate card
3. no card read

### Anything else?

Also I just tried using the Mifare fuzzer and my phone and the Arduino reader picked up nothing. It seems the flipper can read cards but not emulate them. Im on the flipper community page and it says this is a problem since stock firm wear 94 and 93 doesn't have these issues.

**Comment by mgrybyk** [comment]
Does it work for you on 65?

**Comment by Pmacdon15** [comment]
It did not, but I didn't wipe the SD card. Would that have an effect? I also tried with stock 93 and it said there was an api miss match when I tried to use the nfc app. Does updating the firmware automatically update the apps on the SD card or do I have to wipe the SD card and then update the firmware to 65 and see if it works?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Pmacdon15** [comment]
its very strange to me that the issue seems to be happening on the stock firmware after 93 as well.

**Comment by Pmacdon15** [comment]
Withdrawing the issue. Although I can not read emulated on the Arduino, it works on my phone after I took the case off. So I do not believe it is an issue. Sorry again and thank you for your time, great work here.

**Comment by Pmacdon15** [comment]
none issue.
