### ISSUE TITLE
Display Backlight & Bluetooth

### ISSUE THREAD

**Issue by LAZYROO** [DarkFlippers/unleashed-firmware#697]
I downloaded the flipper unleashed and installed it on flipper via my phone. However after I could not use Bluetooth and the backlight won't turn on. I fixed the Bluetooth by factory reset, new SD card, and forgetting the flipper. However my display is still dark and I would like to use unleashed.

**Comment by assasinfil** [comment]
Flash non-rgb version.

**Comment by Leptopt1los** [comment]
@LAZYROO 
1) install any non-r build
2) unpair flipper from phone, phone from flipper, flipper from mobile app. pair flipper and mobile app again

**Comment by LAZYROO** [comment]
Thanks! Just curious,is there a way to install the non RGB via iPhone? The only direct download it will allow is the RGB mode one...
