### ISSUE TITLE
Pcap empty Marauder

### ISSUE THREAD

**Issue by GrAv7sTaR** [DarkFlippers/unleashed-firmware#704]
With the last Unleashed Firmware my pcap file saved in the Sd are empty after sniff with marauder.
Downgrade to 0,69E version of Unleashed solved this problem.

**Comment by xMasterX** [comment]
You need to flash latest firmware on wifi board
Use apps -> gpio -> esp flasher -> Quick flash -> your board -> marauder

071 release uses latest marauder companion that REQUIRES latest Marauder firmware on wifi board
