### ISSUE TITLE
Transparent Flipper RX weak

### ISSUE THREAD

**Issue by DavidIgor** [DarkFlippers/unleashed-firmware#711]
recently i sold white flipper and started using mu original transparent flipper... I noticed that it has weaker receiving capabilities.. especially weather station app, frequency analyzer, or spectrum analyzer are noticeably weaker. I have tested downgrading unleashed fw, reinstalling... (even tested with RM). Im wondering if anyone else having same issue? my previous flipper was around year old (unfortunately I don't have it anymore).

**Comment by DefinetlyNotAI** [comment]
Same here, I have 2 flippers, and 1 is transparent... its significantly weaker than the opaque white version, the transparent is running official firmware, so i dont think that is the issue, (technically waves like IR and Radio etc are absorbed more with black while no absorbtion with transparent)
