### ISSUE TITLE
Support for Video Game Module

### ISSUE THREAD

**Issue by cyrax303** [DarkFlippers/unleashed-firmware#714]
### Description of the feature you're suggesting.

Please insert the possibility for the new Video Game Module.

**Comment by datadotlog** [comment]
It's already to download on app

**Comment by muslimsteel** [comment]
Not sure if I am missing something, but I tried to connect it to a monitor after I downloaded the app and updated the firmware on the module itself, and it says that the module is not initialized and that the firmware on it needs updating. I am on 071 of unleashed

**Comment by maverickk89** [comment]
> Not sure if I am missing something, but I tried to connect it to a monitor after I downloaded the app and updated the firmware on the module itself, and it says that the module is not initialized and that the firmware on it needs updating. I am on 071 of unleashed

try these:
1) connect VGM to flipper
2) install original firmware on flipper
3) install some VGM apps and check everything is working with VGM
4) reinstall unleashed

btw after these steps flipper is stucked with hourglass 
![photo_2024-03-01_16-41-50](https://github.com/DarkFlippers/unleashed-firmware/assets/34450139/7a6ba007-d610-4c1f-b955-47a934ac6694)

**Comment by Leptopt1los** [comment]
@maverickk89 try on latest dev build:
https://dev.unleashedflip.com/

**Comment by muslimsteel** [comment]
Works now on the dev firmware, I will add that I still had to initialize it on the original firmware first and then load back up unleashed. Thanks!
