### ISSUE TITLE
Flipper crashes and reboots after closing Evil Portal.

### ISSUE THREAD

**Issue by Awlexegrecki** [DarkFlippers/unleashed-firmware#724]
### Describe the bug.

 After stopping and exiting evil portal, the flipper crashes and reboots. It shows "NULL pointer dereference". Currently on Unleashed 071e. 

![image](https://github.com/DarkFlippers/unleashed-firmware/assets/79055874/d6308b1a-3b91-4e2e-8141-1db077d077f3)

### Reproduction

1. Switch on
2. Navigate to GPIO Apps
3. Open Evil Portal
4. Start Evil Portal (while Official ESP32 module is plugged in with marauder + evil portal fw)
5. Stop Evil Portal
6. Close Evil Portal

**Comment by vaidasnet** [comment]
Unleashed RIP

**Comment by xMasterX** [comment]
Should be fixed in latest release 072 and dev branch too
