### ISSUE TITLE
SubGhz: Keeloq Novoferm manufacturer protocol support

### ISSUE THREAD

**Issue by cartosco** [DarkFlippers/unleashed-firmware#729]
### Description of the feature you're suggesting.

Add support to decode Novoferm Keeloq devices

**Comment by xMasterX** [comment]
Hello, can you provide RAW recordings of this remote?
3 presses of each button with pause around 2 seconds between each press, you can record them in one raw file

**Comment by stresli** [comment]
remote Novoferm Novotron 502
433.92 AM
Rollingcode Keeloq
66 bit
Encryption/Decryption simple 10 bit

[Remote_NOVOFERM_NOVOTRON_502_MAX43-2.txt](https://github.com/user-attachments/files/15989266/Remote_NOVOFERM_NOVOTRON_502_MAX43-2.txt)
