### ISSUE TITLE
BLE spam doesn't work on Android as suggested.

### ISSUE THREAD

**Issue by MHNiK** [DarkFlippers/unleashed-firmware#731]
### Describe the bug.

All android spams doesn't work. 
Only the Kitchensink triggers something on my S24 Ulta: Galaxy Watch. Every other android spam just don't work, even Google Nearby devices is turned on. 

### Reproduction

BLE Spam -> Android

**Comment by xMasterX** [comment]
Because it was patched in recent android updates, this is not a bug
