### ISSUE TITLE
UMC Gen 4 cart soft brick

### ISSUE THREAD

**Issue by covar2077** [DarkFlippers/unleashed-firmware#738]
I’ve been experimenting with my UMC Gen 4, but now the UID has switched to 11 22 33 44 and my flipper no longer sees it as a UMC Gen 4. I tried to wipe it within the flipper app nfc magic. 

Is it possible to get the card out of recovery mode with the flipper?

**Comment by Leptopt1los** [comment]
@covar2077 install 072 release, go to nfc magic -> gen4 actions -> set default config (if card configured with default password)

**Comment by covar2077** [comment]
Thanks for the reply. I will try it and provide feedback soon.

**Comment by covar2077** [comment]
Thank you @Leptopt1los you are a life saver!!!!
