### ISSUE TITLE
LCD backlight doesnt work. 

### ISSUE THREAD

**Issue by 00ihsan** [DarkFlippers/unleashed-firmware#740]
### Describe the bug.

Flipper screen on and functioning. Only problem is backlight off. I have checked settings and reinstalled. 

Currently running latest r firmware. 

### Reproduction

1. Install new release.

**Comment by Leptopt1los** [comment]
dublicate
https://github.com/DarkFlippers/unleashed-firmware/issues/589
https://github.com/DarkFlippers/unleashed-firmware/issues/563
https://github.com/DarkFlippers/unleashed-firmware/issues/630
https://github.com/DarkFlippers/unleashed-firmware/issues/697
