### ISSUE TITLE
LCD backlight not working in unleashed 071r/072r

### ISSUE THREAD

**Issue by xecaz** [DarkFlippers/unleashed-firmware#747]
### Describe the bug.

Please close this if already known, but since i installed unleashed 071r the LCD backlight is no longer working. Assumed a bug and just updated to 072r but have the same issue. Rolling back to vanilla flipper firmware resolves it. 

### Reproduction

1. unpack new flipper ;)
2. using qflipper on windows, choose to update flipper to custom firmware, select the flipper-z-f7-update-unlshd-071r.tgz/flipper-z-f7-update-unlshd-072r.tgz archive. 
3. Install and reboot.
4. Confirm version reflects that the new firmware is in place, but LCD backlight is no longer working

### Target

bug

**Comment by BrianD436** [comment]
Do you have a modified flipper for RGB? Because if you have not modified it for RGB then you'll have issues. Switch to another release instead.

**Comment by BrianD436** [comment]
Do you have a modified flipper for RGB? Because if you have not modified it for RGB then you'll have issues. Switch to another release instead.

https://github.com/quen0n/flipperzero-firmware-rgb

The r destination is for that.

**Comment by Leptopt1los** [comment]
closing because of @BrianD436 answer

**Comment by xecaz** [comment]
Thanks for clarifying this, was not aware of this mod but now i have something fun to do once back home, RGB modding my flipper. Thanks for the fast turnaround, and sorry for raising this.

**Comment by BrianD436** [comment]
> have

Going forward, read those designations. I use the Extra. It's my favorite.
