### ISSUE TITLE
Modulation analyser in frequency analyser app

### ISSUE THREAD

**Issue by Eng1n33r** [DarkFlippers/unleashed-firmware#751]
### Description of the feature you're suggesting.

Add a modulation analyzer in addition to the frequency analyzer

**Comment by xMasterX** [comment]
Already done in private premium version, also with external module support

**Comment by liszkai** [comment]
> Already done in private premium version, also with external module support

How can we subscribe to premium version?

**Comment by xMasterX** [comment]
> > Already done in private premium version, also with external module support
> 
> How can we subscribe to premium version?

This was trolling, we don't have any closed source shit or "premium" versions
