### ISSUE TITLE
Sub-GHz External C1101 Module Selectability

### ISSUE THREAD

**Issue by hotdjdave** [DarkFlippers/unleashed-firmware#752]
### Describe the bug.

There used to be a setting under **Sub-GHz** > **Radio Settings** > **Module** which listed the selectable options "**Internal**" and "**External**." **External** was the way to enable an _external_ antenna (or C1101 module) and, at least to me, ensured it was using the external antenna and not the internal one. Now, going here only shows "**Internal**" and no option to select "**External**." Why was this taken away?

There should be some indication on Flipper letting you know if the internal C1101 module is being use or an external one is used.****

### Reproduction

1. Sub-GHz
2. Radio Settings
3. Module

**Comment by xMasterX** [comment]
Hi, External menu item appears only when external module is connected before launching subghz app, if module was not detected there will be no External option in menu

If module is not detected that means you have bad contact or module is broken

Nothing was "taken away" or "removed" from firmware

**Comment by hotdjdave** [comment]
My new flipper arrived two days ago (May 14) and a new (not yet used) cc1101 module.  The same issue.  The "Internal" setting is the only option.  I have been using my other Flipper along with a euerodesign C1101 module for a couple of years with no issues.  I am not sure if this new(er) "auto detect" feature is the cause, but it seems to be the only variable that has changed.  **_NEW_** FLIPPER and **_NEW_** CC1101 MODULE and still **no** "EXTERNAL" option.
