### ISSUE TITLE
Selecting External Antenna - Sub-GHz External C1101 Module

### ISSUE THREAD

**Issue by hotdjdave** [DarkFlippers/unleashed-firmware#754]
### Describe the bug.

This is in response to a previous issue I posted and was closed:  "Sub-GHz External C1101 Module Selectability" #752.  

New info: 

My new flipper arrived a few days ago (May 14, 2024) and I made use of a new (not yet used) cc1101 module. The same issue persists. The "Internal" setting is the only option. I have been using my other/older Flipper along with a euerodesign C1101 module for a couple of years with no issues. I am not sure if this new(er) "auto detect" feature is the cause, but it seems to be the only variable that has changed. 

To reiterate:  I got a NEW FLIPPER and used NEW CC1101 MODULE, and still no "EXTERNAL" option. 

This issue remains unresolved.  Thanks.

Text from original post:

> There used to be a setting under Sub-GHz > Radio Settings > Module which listed the selectable options "Internal" and "External." External was the way to enable an external antenna (or C1101 module) and, at least to me, ensured it was using the external antenna and not the internal one. Now, going here only shows "Internal" and no option to select "External." Why was this taken away?
> 
> There should be some indication on Flipper letting you know if the internal C1101 module is being use or an external one is used.****

Response:

> Hi, External menu item appears only when external module is connected before launching subghz app, if module was not detected there will be no External option in menu
> 
> If module is not detected that means you have bad contact or module is broken
> 
> Nothing was "taken away" or "removed" from firmware

Yes, the ability to manually select "External" or "Internal" was taken away.  It is no longer an option.  

### Reproduction

1. Sub-GHz
2. Radio Settings
3. Module

### Anything else?

Suggestion:  There should be some indication on Flipper letting you know if the internal C1101 module is being use or an external one is used.

**Comment by xMasterX** [comment]
Hi, stop spamming with the issue or you will be blocked
First of all, you didn't read my previous response, let me repeat, nothing was removed or changed in terms of support of external modules
Your argument that flipper and module is new is not correct
Problem is - your cc1101 external module, replace it or verify it has good contact
"Auto detect" exist for more than half a year already, this isn't new
> Suggestion: There should be some indication on Flipper letting you know if the internal C1101 module is being use or an external one is used.

If you haven't noticed this also is present for more than a year, it was added when we made our first external module support
Indication is present in almost every place and also custom plugins too, saying "Int" or "Ext" in the corner of the screen

**Comment by hotdjdave** [comment]
Sorry. I wasn't trying to spam. But I literally used a BRAND NEW Flipper Zero device and a new (never used) CC1101 module, and still don't see the "External" option. I don't really see what anyone else could do to prove there is an issue other than tech lab the problem.

What else would you suggest.
