### ISSUE TITLE
no sub-ghz reader and many api's crash 

### ISSUE THREAD

**Issue by KissingSisters** [DarkFlippers/unleashed-firmware#758]
### Describe the bug.

many of the API's (mitsubishi ac remote, xbox controller) report API needs to be updated or hard crash flipper device. 

No sub-ghz reader in menu anymore only tools like protopager but the ability to read is gone. 

### Reproduction

nav to sub-ghz and look for tradtonal reader. 

try to run various controllers in infrared like mitsubishi ac or xbox

**Comment by xMasterX** [comment]
Hello, this is user related issue, install update properly following instructions, links can be found in every release and in main README file
Also I recommend in your case, removing `apps` folder from your microsd before installing update

**Comment by KissingSisters** [comment]
I've installed unleashed many times and followed the instructions I get what you're saying about sub-ghz but the various tools having broken apis that hard crash flipper is not a user or install issue, please resolve

**Comment by KissingSisters** [comment]
Deleting the apps folder and reinstalling worked thanks I didn't/ I'm not seeing the delete apps folder as a step on the read me and those tools still worked on version 73 but thanks none the less
