### ISSUE TITLE
NFC - Write to initial card CRASH "UsageFault"

### ISSUE THREAD

**Issue by juansonnn** [DarkFlippers/unleashed-firmware#772]
### Describe the bug.

I've saved an NFC card, i have all the keys. 
After that, i've modified the content of the card (not of the saved image).
Then, I wanted to write the original image of the NFC card to the same card. 
BUG: it crashs when reading the original NFC card.

### Reproduction

1. read an NFC CARD MIFARE Classic 1K
2. save its image
3. modified the content of the NFC card (not the image you saved in the flipper)
4. try to write the same card with the image you previously saved.
5. It crashes

**Comment by AztecCodes** [comment]
I think you can't override the NFC Card on this way. It should be possible with NFC Magic Cards.
You can't override "normal" NFC Cards. You need to buy NFC Magic Cards and write the modified data onto a Magic card.
