### ISSUE TITLE
NFC - default key file from already found A+B Keys

### ISSUE THREAD

**Issue by 23tom2323** [DarkFlippers/unleashed-firmware#803]
Hello,
When I read a Mifare Classic card (approximately 2 hours), it saves the A and B keys under nfc/cache/ UID of the card .keys (2A1FCE33.keys)

With another card from the same system it would take another 2 hours with the same A and B key.

Is there a way to save the keys found in a file? Something like a default key file? Before it takes another 2 hours.

**Comment by xMasterX** [comment]
Add that keys into user dict at the top of the file, so they will be checked first
You can do that on flipper itself via Extra actions
Or via PC

**Comment by 23tom2323** [comment]
Big Thx
