### ISSUE TITLE
Implementation of MIFARE Classic research paper findings

### ISSUE THREAD

**Issue by dawkacz** [DarkFlippers/unleashed-firmware#824]
### Description of the feature you're suggesting.

There is this article about new methods of cloning MIFARE Classic cards with source code examples.

https://eprint.iacr.org/2024/1275.pdf

Is this possible to implement this to Unleashed firmware?

**Comment by xMasterX** [comment]
Impemented by noproto in OFW and in latest unleashed release, update and try reading card

Also there is a guide for new NFC attacks:
https://gist.github.com/noproto/7f0481ac1588a4d0cd7bdea06b63dfb6
