### ISSUE TITLE
Sub-ghz app is stuck and crashed then if GPIO module is removed while reading mode 

### ISSUE THREAD

**Issue by usmanovbf** [DarkFlippers/unleashed-firmware#846]
### Describe the bug.

I use E07-433M20S module to read keys. And if I lost connection with the GPIO module, the app is stuck and only flipper zero reloading helps me 

### Reproduction

1. Go to Read mode in Sub-ghz with some external GPIO module for that purpose, e. g. E07-433M20S
2. Unplug module or lost connection in any way
3. Get sticked device 

### Target

Unleashed 079e

### Anything else?

It would be great to switch between internal and external (GPIO) antennas if module is disconnected and connected back respectively.
And this [addition](https://github.com/DarkFlippers/unleashed-firmware/issues/845) would help to save all found keys at the same time

**Comment by xMasterX** [comment]
Try removing RAM from running PC, anything good will happen? No
Same goes with flipper GPIO, its not an USB, this has no protection
When module IS running it has active SPI line communication, if it breaks we crash since something is wrong, there's no hotswap for modules
