### ISSUE TITLE
Incorrect amount of combinations in BF existing dump option

### ISSUE THREAD

**Issue by jasniec** [DarkFlippers/unleashed-firmware#94]
### Describe the bug.

Hi all,
I wanted to try brute force for one of the SubGhz message I saved.  For different devices, last word (2 hex characters) changes, therefore there are 256 possibilities (00 - FF), but the SubBrute generates only 64 of them. I tried a couple of captures from this device (different two characters) and the issue appears for all of them.
![image](https://user-images.githubusercontent.com/16793279/194760416-ebda274d-4452-49a5-b378-ec48ea7cf962.png)
![image](https://user-images.githubusercontent.com/16793279/194760371-b89582d5-9350-4cea-b687-74551c50fe4c.png)

### Reproduction

1. Add subGHz file with following content:
```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: Princeton
Bit: 24
Key: 00 00 00 00 00 71 40 40
TE: 226
```
2. Open Bruteforcer app and open the file
3. Choose last word (40) and press select

### Target

Sub-GHz Bruteforcer

**Comment by xMasterX** [comment]
Known issue, it skips values after reaching 63 so its lowered to that value now
New version of subghz bruteforcer is coming, just wait a bit, it will address that issue too

**Comment by xMasterX** [comment]
Fixed with new subghz bruteforcer version
